Repository mitodl/open-discussions, pull requests merged in 2018-08, with the labels that each got.

#1014 Update the urlHostname function to remove www. from beginning of domains
  static/js/lib/url.js
  static/js/lib/url_test.js
Labels: Waiting on Author

#1009 Use urls with post slugs in emails
  mail/templates/comments/body.html
  mail/templates/frontpage/body.html
  notifications/notifiers/frontpage_test.py
  open_discussions/urls.py
  open_discussions/urls_test.py
Labels: Waiting on Author

#1020 Hide comment section header when post has no comments
  static/js/containers/PostPage.js
  static/js/containers/PostPage_test.js
Labels: Waiting on Author

#1018 Notify user via snackbar when URL is copied
  static/js/components/SharePopup.js
  static/js/components/SharePopup_test.js
Labels: Waiting on Author

#1023 link names to profile in comment and post displays
  static/js/components/CommentTree.js
  static/js/components/CommentTree_test.js
  static/js/components/CompactPostDisplay.js
  static/js/components/CompactPostDisplay_test.js
  static/js/components/ExpandedPostDisplay.js
  static/js/components/ExpandedPostDisplay_test.js
  static/scss/post.scss
Labels: Waiting on Author

#1015 Touched up account settings UI and added SAML auth type
  authentication/views.py
  authentication/views_test.py
  open_discussions/factories.py
  static/js/components/ExternalLogins.js
  static/js/containers/AccountSettingsPage.js
  static/js/containers/AccountSettingsPage_test.js
  static/js/flow/discussionTypes.js
  static/js/lib/api.js
  static/scss/basic.scss
  static/scss/form.scss
  static/scss/settings.scss
Labels: Waiting on Author

#959 Added API change to support prompting the user to login via MM
  authentication/exceptions.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  authentication/serializers.py
  authentication/serializers_test.py
  authentication/utils.py
  authentication/views_test.py
  cassettes/authentication.views_test.test_login_register_flows[login_email_mm_only].json
  factory_data/authentication.views_test.test_login_register_flows[login_email_mm_only].json
  open_discussions/settings.py
Labels: Waiting on Author

#1026 Added a setting to change the default for feature flags
  docker-compose.yml
  open_discussions/features.py
  open_discussions/features_test.py
  open_discussions/settings.py
Labels: Waiting on Author

#1017 Add can_remove field to serializers
  cassettes/channels.views.moderators_test.test_add_moderator.json
  cassettes/channels.views.moderators_test.test_add_moderator_again.json
  cassettes/channels.views.moderators_test.test_add_moderator_email.json
  cassettes/channels.views.moderators_test.test_list_moderators.json
  cassettes/channels.views.moderators_test.test_list_moderators_many_moderator.json
  cassettes/channels.views.moderators_test.test_list_moderators_moderator.json
  cassettes/channels.views.moderators_test.test_list_moderators_staff.json
  channels/api.py
  channels/api_test.py
  channels/serializers.py
  channels/serializers_test.py
  channels/views/moderators.py
  channels/views/moderators_test.py
  factory_data/channels.views.moderators_test.test_add_moderator.json
  factory_data/channels.views.moderators_test.test_add_moderator_again.json
  factory_data/channels.views.moderators_test.test_add_moderator_email.json
  factory_data/channels.views.moderators_test.test_list_moderators.json
  factory_data/channels.views.moderators_test.test_list_moderators_many_moderator.json
  factory_data/channels.views.moderators_test.test_list_moderators_moderator.json
  factory_data/channels.views.moderators_test.test_list_moderators_staff.json
Labels: Waiting on Author

#1028 Added some PR template checkboxes
  pull_request_template.md
Labels: Waiting on Author

#1033 Added redirect for new JWT tokens to /complete/provider
  open_discussions/views.py
  open_discussions/views_test.py
Labels: Waiting on Author

#1027 Added redirect to MM on login
  authentication/backends/micromasters.py
  static/js/containers/App.js
  static/js/containers/auth/LoginProviderRequiredPage.js
  static/js/containers/auth/LoginProviderRequiredPage_test.js
  static/js/flow/authTypes.js
  static/js/lib/auth.js
  static/js/lib/auth_test.js
  static/js/lib/url.js
  static/js/reducers/auth.js
Labels: Needs Review

#1024 Improvements to moderator/contributor UI
  static/js/actions/ui.js
  static/js/components/admin/MembersList.js
  static/js/components/admin/MembersList_test.js
  static/js/containers/PostPage_test.js
  static/js/containers/ProfileImage_test.js
  static/js/containers/admin/EditChannelContributorsPage.js
  static/js/containers/admin/EditChannelContributorsPage_test.js
  static/js/containers/admin/EditChannelModeratorsPage.js
  static/js/containers/admin/EditChannelModeratorsPage_test.js
  static/js/factories/channels.js
  static/js/flow/discussionTypes.js
  static/js/reducers/ui.js
  static/js/reducers/ui_test.js
  static/scss/admin.scss
Labels: Waiting on Author

#1032 Changed unrecognized email UX to a validation message
  authentication/serializers.py
  authentication/views_test.py
  cassettes/authentication.views_test.test_login_register_flows[login_email_not_exists].json
  static/js/containers/auth/LoginPage.js
  static/js/containers/auth/LoginPage_test.js
  static/js/containers/auth/RegisterPage.js
  static/js/containers/auth/RegisterPage_test.js
Labels: Waiting on Author

#1040 Added WrappedComponent to our HOCs and taught the helper render how to traverse
  static/js/hoc/withChannelSidebar.js
  static/js/hoc/withCommentModeration.js
  static/js/hoc/withForm.js
  static/js/hoc/withPostModeration.js
  static/js/hoc/withSingleColumn.js
  static/js/util/integration_test_helper.js
Labels: Waiting on Author

#1031 Move container level form code out of ProfileImage
  static/js/actions/ui.js
  static/js/components/ImageUploaderForm.js
  static/js/containers/ImageUploader.js
  static/js/containers/ProfileImage.js
  static/js/containers/ProfileImage_test.js
  static/js/flow/discussionTypes.js
  static/js/lib/profile.js
Labels: Waiting on Author

#1038 Login button on header
  static/js/components/Toolbar.js
  static/js/components/Toolbar_test.js
  static/scss/navigation.scss
Labels: Needs Review

#1041 Fixed snackbar UI bugs
  static/js/components/material/Snackbar.js
  static/js/containers/App.js
  static/scss/_variables.scss
  static/scss/banner.scss
  static/scss/createPost.scss
  static/scss/form.scss
  static/scss/layout.scss
  static/scss/snackbar.scss
Labels: Waiting on Author

#1044 Silence warning with empty profile fields
  static/js/components/ProfileForm.js
  static/js/components/ProfileForm_test.js
Labels: Needs Review

#1043 Fixed contributor and moderator factories for username collisions
  static/js/factories/channels.js
Labels: Waiting on Author

#1030 Display author headline near name on post cards, limit length of headline text
  cassettes/channels.views.posts_test.test_get_post_no_profile.json
  channels/serializers.py
  channels/views/frontpage_test.py
  channels/views/posts_test.py
  channels/views/reports_test.py
  factory_data/channels.views.posts_test.test_get_post_no_profile.json
  profiles/migrations/0008_profile_headline_length.py
  profiles/models.py
  static/js/components/CompactPostDisplay.js
  static/js/components/CompactPostDisplay_test.js
  static/js/components/ExpandedPostDisplay.js
  static/js/components/ExpandedPostDisplay_test.js
  static/js/components/ProfileForm.js
  static/js/factories/comments.js
  static/js/factories/posts.js
  static/js/flow/discussionTypes.js
  static/scss/post.scss
Labels: Waiting on Author

#1019 Enable channel-specific google analytics tracking
  channels/admin.py
  channels/factories.py
  channels/migrations/0008_channel_ga_tracking_id.py
  channels/models.py
  channels/serializers.py
  channels/serializers_test.py
  channels/views/channels_test.py
  static/js/containers/ChannelPage.js
  static/js/containers/PostPage.js
  static/js/factories/channels.js
  static/js/flow/discussionTypes.js
  static/js/hoc/withChannelTracker.js
  static/js/hoc/withChannelTracker_test.js
  static/js/lib/test_utils.js
  static/js/util/withTracker_test.js
Labels: Waiting on Author

#1021 fix typo in error log
  search/indexing_api.py
Labels: Waiting on Author

#1039 Changed login UI to show image & name when email entered
  authentication/views.py
  authentication/views_test.py
  profiles/serializers.py
  static/js/containers/auth/LoginPasswordPage.js
  static/js/containers/auth/LoginPasswordPage_test.js
  static/js/flow/authTypes.js
  static/js/lib/api.js
  static/js/lib/auth.js
  static/js/reducers/auth.js
  static/scss/form.scss
  static/scss/profile-image.scss
Labels: Waiting on Author

#1060 Added well-named urls to urls.py
  open_discussions/urls.py
Labels: Needs Review

#1046 Updated staff permission to check user.is_staff for authenticated users
  channels/views/channels.py
  channels/views/moderators.py
  channels/views/reports.py
  channels/views/subscribers.py
  fixtures/reddit.py
  fixtures/users.py
  open_discussions/permissions.py
  open_discussions/permissions_test.py
  profiles/permissions.py
Labels: Needs Review

#983 Implement uploading channel avatar and banner
  channels/serializers.py
  static/images/channel_avatar_default.svg
  static/images/channel_banner_default.svg
  static/js/components/CropperWrapper.js
  static/js/components/ImageUploaderForm.js
  static/js/components/ImageUploaderForm_test.js
  static/js/components/admin/EditChannelAppearanceForm.js
  static/js/components/admin/EditChannelAppearanceForm_test.js
  static/js/containers/ChannelAvatar.js
  static/js/containers/ChannelAvatar_test.js
  static/js/containers/ChannelBanner.js
  static/js/containers/ChannelBanner_test.js
  static/js/containers/ImageUploader.js
  static/js/containers/ImageUploader_test.js
  static/js/containers/ProfileImage.js
  static/js/containers/ProfileImage_test.js
  static/js/containers/admin/EditChannelAppearancePage.js
  static/js/containers/admin/EditChannelAppearancePage_test.js
  static/js/factories/channels.js
  static/js/flow/discussionTypes.js
  static/js/hoc/withForm.js
  static/js/lib/api.js
  static/js/lib/redux_rest.js
  static/js/lib/util.js
  static/js/reducers/channel_avatar.js
  static/js/reducers/channel_banner.js
  static/js/util/integration_test_helper.js
  static/scss/admin.scss
  static/scss/form.scss
Labels: Waiting on Author

#1070 Add upload_to to banner and avatar
  channels/migrations/0009_avatar_banner_filename.py
  channels/models.py
  channels/views/channels_test.py
  profiles/utils.py
  profiles/utils_test.py
Labels: Waiting on Author

#1071 Remove edit button from profile image on profile view page
  static/js/components/ProfileForm_test.js
  static/js/containers/ProfilePage.js
  static/js/containers/ProfilePage_test.js
Labels: Waiting on Author

#1073 Update edit profile form to match design
  static/js/components/ProfileForm.js
  static/js/components/ProfileForm_test.js
  static/scss/form.scss
  static/scss/profile.scss
Labels: Waiting on Author

#1076 Fixed redirect on expired JWT
  open_discussions/views.py
Labels: Work in Progress

#1081 Fix profile image upload bug
  static/js/components/ProfileForm.js
  static/js/containers/ProfileImage.js
  static/js/containers/ProfileImage_test.js
  static/scss/basic.scss
Labels: Needs Review

#1079 Remove IS_OSX since it's unnecessary with Docker for Mac
  scripts/envs.sh
  webpack_dev_server.sh
Labels: Waiting on Author

#1055 Banner message if creating a post on reddit fails
  static/js/components/CommentForms.js
  static/js/components/CommentForms_test.js
  static/js/containers/CreatePostPage.js
  static/js/containers/CreatePostPage_test.js
Labels: Waiting on Author

#1083 Use embedly image api to resize thumbnails in Embedly component
  static/js/components/Embedly.js
  static/js/components/Embedly_test.js
  static/js/lib/url.js
  static/js/lib/url_test.js
Labels: Needs Review

#981 prosemirror editor
  package.json
  static/js/babelhook.js
  static/js/components/AddLinkMenu.js
  static/js/components/AddLinkMenu_test.js
  static/js/components/CloseButton.js
  static/js/components/CloseButton_test.js
  static/js/components/CreatePostForm.js
  static/js/components/CreatePostForm_test.js
  static/js/components/Editor.js
  static/js/components/Editor_test.js
  static/js/components/ExpandedPostDisplay_test.js
  static/js/containers/CreatePostPage_test.js
  static/js/global_init.js
  static/js/lib/prosemirror.js
  static/js/lib/util.js
  static/js/lib/util_test.js
  static/scss/add-link-menu.scss
  static/scss/close-button.scss
  static/scss/create-post.scss
  static/scss/editor.scss
  static/scss/layout.scss
  yarn.lock
Labels: Waiting on Author

#1090 Show domain and link icon next to post title
  static/js/components/ExpandedPostDisplay_test.js
  static/js/lib/posts.js
  static/js/lib/posts_test.js
  static/scss/post.scss
Labels: Waiting on Author

#1092 Upgrade to Django 2.1
  authentication/urls.py
  channels/models.py
  embedly/views_test.py
  fixtures/common.py
  open_discussions/settings.py
  open_discussions/templatetags/render_bundle.py
  profiles/models.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1086 Add avatar_small and avatar_medium
  channels/migrations/0010_avatar_small_medium.py
  channels/models.py
  channels/serializers.py
  channels/serializers_test.py
  channels/utils.py
  channels/views/channels_test.py
  profiles/utils.py
Labels: Waiting on Author

#1096 Upgrade deps
  requirements.in
  requirements.txt
  test_requirements.txt
Labels: Waiting on Author

#1082 Add channel avatar to sidebar
  static/js/components/Navigation.js
  static/js/components/Navigation_test.js
  static/js/components/SubscriptionsList.js
  static/js/components/SubscriptionsList_test.js
  static/js/components/admin/EditChannelAppearanceForm.js
  static/js/containers/ChannelAvatar.js
  static/js/containers/ChannelAvatar_test.js
  static/js/containers/ChannelBanner.js
  static/js/factories/channels.js
  static/js/flow/discussionTypes.js
  static/scss/admin.scss
  static/scss/channel.scss
  static/scss/navigation.scss
Labels: Needs Review

#1089 Move footer into sidebar
  static/images/mit-logo-darkgrey.svg
  static/js/components/Footer.js
  static/js/containers/App.js
  static/js/containers/Drawer.js
  static/scss/footer.scss
  static/scss/layout.scss
  static/scss/navigation.scss
Labels: Waiting on Author

#1102 Login popup for anonymous user vote buttons on post detail page
  package.json
  static/js/components/Button.js
  static/js/components/CommentVoteForm.js
  static/js/components/CommentVoteForm_test.js
  static/js/components/LoginPopup.js
  static/js/components/LoginPopup_test.js
  static/js/components/SharePopup.js
  static/js/lib/posts.js
  static/js/lib/posts_test.js
  static/scss/share-popup.scss
  yarn.lock
Labels: Needs Review

#1099 Show snackbar when user adds/removes a moderator/contributor
  static/js/components/admin/MembersList.js
  static/js/components/admin/MembersList_test.js
  static/js/containers/admin/EditChannelContributorsPage.js
  static/js/containers/admin/EditChannelContributorsPage_test.js
  static/js/containers/admin/EditChannelModeratorsPage.js
  static/js/containers/admin/EditChannelModeratorsPage_test.js
  static/js/hoc/withSingleColumn.js
Labels: Needs Review

#1108 Make home link full width
  static/js/components/Footer.js
  static/scss/navigation.scss
Labels: Waiting on Author

#1110 add material grid
  package.json
  static/js/components/Grid.js
  static/js/components/Grid_test.js
  static/js/containers/ChannelPage_test.js
  static/js/containers/PostPage_test.js
  static/js/hoc/withChannelSidebar.js
  static/js/hoc/withSingleColumn.js
  static/scss/layout.scss
Labels: Waiting on Author

#1111 Replace withLoading with Loading component
  static/js/components/Loading.js
  static/js/components/Loading_test.js
  static/js/containers/ChannelModerationPage.js
  static/js/containers/ChannelPage.js
  static/js/containers/HomePage.js
  static/js/containers/PostPage.js
  static/js/containers/ProfileEditPage.js
  static/js/containers/ProfilePage.js
  static/js/containers/auth/RegisterConfirmPage.js
  static/js/containers/auth/RegisterConfirmPage_test.js
Labels: Waiting on Author

#1120 Fix sidebar scrolling
  static/scss/navigation.scss
Labels: Waiting on Author

#1121 Revert "Replace withLoading with Loading component (#1111)"
  static/js/components/Loading.js
  static/js/components/Loading_test.js
  static/js/containers/ChannelModerationPage.js
  static/js/containers/ChannelPage.js
  static/js/containers/HomePage.js
  static/js/containers/PostPage.js
  static/js/containers/ProfileEditPage.js
  static/js/containers/ProfilePage.js
  static/js/containers/auth/RegisterConfirmPage.js
  static/js/containers/auth/RegisterConfirmPage_test.js
Labels: Waiting on Author

#1123 remove problematic CSS to fix scrolling
  static/js/containers/Drawer.js
  static/scss/navigation.scss
Labels: Waiting on Author

#1106 LoginPopup for Follow button
  static/js/components/ExpandedPostDisplay.js
  static/js/components/ExpandedPostDisplay_test.js
  static/js/components/FollowButton.js
  static/js/components/FollowButton_test.js
  static/js/components/LoginPopup.js
  static/js/components/LoginPopup_test.js
  static/scss/layout.scss
  static/scss/popup.scss
Labels: Needs Review

#1093 Make Session auth take priority over JWT tokens
  channels/views/channels_test.py
  channels/views/comments_test.py
  channels/views/contributors_test.py
  channels/views/frontpage_test.py
  channels/views/moderators_test.py
  channels/views/posts_test.py
  channels/views/reports_test.py
  channels/views/subscribers_test.py
  embedly/views_test.py
  fixtures/users.py
  open_discussions/constants.py
  open_discussions/exceptions.py
  open_discussions/permissions.py
  open_discussions/permissions_test.py
  open_discussions/settings.py
  profiles/permissions_test.py
  profiles/views.py
  profiles/views_test.py
  static/js/containers/PostPage.js
  static/js/containers/PostPage_test.js
  static/js/lib/fetch_auth.js
  static/js/lib/fetch_auth_test.js
  static/js/util/rest.js
  static/js/util/rest_test.js
Labels: Waiting on Author

#1101 Fixed incorrect password UI bug
  static/js/actions/ui.js
  static/js/containers/PasswordChangePage_test.js
  static/js/containers/auth/LoginPage.js
  static/js/containers/auth/LoginPage_test.js
  static/js/containers/auth/LoginPasswordPage.js
  static/js/containers/auth/LoginPasswordPage_test.js
  static/js/containers/auth/PasswordResetConfirmPage_test.js
  static/js/containers/auth/PasswordResetPage_test.js
  static/js/containers/auth/RegisterDetailsPage_test.js
  static/js/containers/auth/RegisterPage_test.js
  static/js/reducers/auth.js
  static/js/reducers/ui.js
Labels: Waiting on Author

#1134 upgrade to latest version of Babel
  package.json
  scripts/repl.js
  static/js/babelhook.js
  static/js/components/Editor.js
  webpack.config.prod.js
  webpack.config.shared.js
  yarn.lock
Labels: Waiting on Author

#1141 add material dropdown for picking sort method
  package.json
  static/js/components/SortPicker.js
  static/js/components/SortPicker_test.js
  static/js/containers/ChannelPage_test.js
  static/js/containers/HomePage_test.js
  static/js/containers/PostPage.js
  static/js/containers/PostPage_test.js
  static/js/lib/sorting.js
  static/scss/channel.scss
  static/scss/comment.scss
  static/scss/form.scss
  static/scss/layout.scss
  static/scss/post-list.scss
  static/scss/post.scss
  static/scss/sort-picker.scss
  yarn.lock
Labels: Waiting on Author

#1145 Fixed overflow scrolling to only be vertical
  static/scss/navigation.scss
Labels: Waiting on Author

#1139 Configured login flow to show greeting for external auth providers
  authentication/exceptions.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  authentication/serializers.py
  authentication/views.py
  authentication/views_test.py
  cassettes/authentication.views_test.test_login_register_flows[login_email_saml_exists].json
  factory_data/authentication.views_test.test_login_register_flows[login_email_saml_exists].json
  open_discussions/factories.py
  open_discussions/settings.py
  static/js/components/ExternalLogins.js
  static/js/components/ExternalLogins_test.js
  static/js/components/auth/LoginGreeting.js
  static/js/components/auth/LoginGreeting_test.js
  static/js/components/auth/TouchstoneLoginButton.js
  static/js/containers/auth/LoginPasswordPage.js
  static/js/containers/auth/LoginPasswordPage_test.js
  static/js/containers/auth/LoginProviderRequiredPage.js
  static/js/containers/auth/LoginProviderRequiredPage_test.js
  static/js/containers/auth/RegisterPage.js
  static/js/lib/validation.js
  static/js/lib/validation_test.js
Labels: Waiting on Author

#1142 Add Raven.js
  open_discussions/templates/base.html
  open_discussions/views.py
  open_discussions/views_test.py
  package.json
  static/js/entry/root.js
  static/js/flow/declarations.js
  yarn.lock
Labels: Needs Review

#1136 Added command and tasks to backpopulate a default channel's subscribers
  app.json
  channels/management/commands/backpopulate_default_channel.py
  channels/tasks.py
  channels/tasks_test.py
  notifications/api.py
  open_discussions/settings.py
  open_discussions/utils.py
Labels: Waiting on Author

#1146 standard test pattern for 'shallow' rendered tests
  static/js/components/AddLinkMenu_test.js
  static/js/components/ChannelSidebar_test.js
  static/js/components/CloseButton_test.js
  static/js/components/CommentRemovalForm_test.js
  static/js/components/CommentVoteForm_test.js
  static/js/components/CreatePostForm_test.js
  static/js/components/ExternalLogins_test.js
  static/js/components/LoginPopup_test.js
  static/js/components/Navigation_test.js
  static/js/components/PostListNavigation_test.js
  static/js/components/PostList_test.js
  static/js/components/ReportForm_test.js
  static/js/components/SortPicker_test.js
  static/js/components/SubscriptionsList_test.js
  static/js/components/UserMenu_test.js
  static/js/lib/test_utils.js
Labels: Waiting on Author

#1150 Add handling for AuthorizationFailed on expired JWTs
  static/js/lib/fetch_auth.js
  static/js/lib/fetch_auth_test.js
  static/js/util/rest.js
  static/js/util/rest_test.js
Labels: Waiting on Author
