Repository mitodl/open-discussions, pull requests merged in 2018-04, with the labels that each got.

#579 Fix 401 auth errors
  channels/api.py
  channels/api_test.py
Labels: Needs Review

#582 fix missing profile picture in email
  channels/serializers.py
  channels/views/posts_test.py
Labels: Waiting on Author

#546 add a link to the settings
  static/js/components/Navigation.js
  static/js/components/Navigation_test.js
  static/scss/navigation.scss
Labels: Blocked, Work in Progress

#591 Changing logo and intro paragraph in micromasters digest emails
  mail/templates/email_base.html
  mail/templates/frontpage/body.html
  static/images/mit-logo-micromasters.jpg
Labels: Waiting on Author

#594 Adds a read more button to digest email
  mail/templates/email_base.html
  mail/templates/frontpage/body.html
Labels: Needs Review

#589 Fixed safe_format_recipients to quote display name
  mail/api.py
  mail/api_test.py
Labels: Waiting on Author

#614 add an error page for 403 responses
  static/js/components/404.js
  static/js/components/ErrorPages.js
  static/js/components/Loading.js
  static/js/components/Loading_test.js
  static/js/containers/ChannelModerationPage.js
  static/js/containers/ChannelPage.js
  static/js/containers/ChannelPage_test.js
  static/js/containers/PostPage.js
  static/js/containers/PostPage_test.js
  static/js/hoc/withPostModeration.js
  static/js/util/rest.js
  static/js/util/rest_test.js
Labels: Waiting on Author

#613 Fix button styles on frontpage digest
  mail/templates/email_base.html
  mail/templates/frontpage/body.html
Labels: Waiting on Author

#561 Send emails to subscribers on new comment
  cassettes/notifications.notifiers.comments_test.test_send_notification[False].json
  cassettes/notifications.notifiers.comments_test.test_send_notification[True].json
  channels/conftest.py
  channels/factories.py
  channels/serializers.py
  channels/test_utils.py
  channels/urls_test.py
  channels/views/channels_test.py
  channels/views/comments.py
  channels/views/comments_test.py
  channels/views/contributors_test.py
  channels/views/frontpage_test.py
  channels/views/moderators_test.py
  channels/views/posts_test.py
  channels/views/reports_test.py
  channels/views/subscribers_test.py
  channels/views_test.py
  conftest.py
  factory_data/notifications.notifiers.comments_test.test_send_notification[False].json
  factory_data/notifications.notifiers.comments_test.test_send_notification[True].json
  fixtures/__init__.py
  fixtures/betamax.py
  fixtures/common.py
  fixtures/reddit.py
  fixtures/users.py
  mail/api.py
  mail/templates/comments/body.html
  mail/templates/comments/subject.txt
  mail/templates/email_base.html
  mail/templates/frontpage/body.html
  notifications/api.py
  notifications/api_test.py
  notifications/factories.py
  notifications/migrations/0004_add_comment_event.py
  notifications/models.py
  notifications/models_test.py
  notifications/notifiers/base.py
  notifications/notifiers/base_test.py
  notifications/notifiers/comments.py
  notifications/notifiers/comments_test.py
  notifications/notifiers/email.py
  notifications/notifiers/email_test.py
  notifications/notifiers/frontpage.py
  notifications/notifiers/frontpage_test.py
  notifications/tasks.py
  notifications/tasks_test.py
  notifications/views_test.py
  open_discussions/features.py
  open_discussions/urls.py
  open_discussions/urls_test.py
  open_discussions/views_test.py
  profiles/views_test.py
  pytest.ini
  requirements.in
  requirements.txt
Labels: Needs Review

#622 Add missing environment variable for Travis
  docker-compose.travis.yml
Labels: Needs Review

#625 Fix failing test
  notifications/notifiers/base_test.py
Labels: Needs Review

#593 add follow button to posts and comments
  static/js/components/CommentTree.js
  static/js/components/CommentTree_test.js
  static/js/components/ExpandedPostDisplay.js
  static/js/components/ExpandedPostDisplay_test.js
  static/js/containers/PostPage.js
  static/js/factories/comments.js
  static/js/factories/comments_test.js
  static/js/factories/posts.js
  static/js/factories/posts_test.js
  static/js/flow/discussionTypes.js
  static/js/util/api_actions.js
  static/js/util/api_actions_test.js
  static/scss/_variables.scss
  static/scss/comment.scss
  static/scss/post.scss
Labels: Blocked, Waiting on Author

#597 add comment / post settings
  package.json
  scripts/test/js_test.sh
  static/js/containers/App_test.js
  static/js/containers/SettingsPage.js
  static/js/containers/SettingsPage_test.js
  static/js/factories/settings.js
  static/js/factories/settings_test.js
  static/js/lib/api.js
  static/js/lib/api_test.js
  static/js/reducers/settings.js
  static/scss/layout.scss
  static/scss/settings.scss
  yarn.lock
Labels: Blocked, Waiting on Author

#626 Allow anonymous access for channels
  cassettes/channels.views.channels_test.test_get_channel_anonymous[False].json
  cassettes/channels.views.channels_test.test_get_channel_anonymous[True].json
  cassettes/channels.views.channels_test.test_list_channels_anonymous[False].json
  cassettes/channels.views.channels_test.test_list_channels_anonymous[True].json
  channels/api.py
  channels/api_test.py
  channels/views/channels.py
  channels/views/channels_test.py
  factory_data/channels.views.channels_test.test_get_channel_anonymous[False].json
  factory_data/channels.views.channels_test.test_get_channel_anonymous[True].json
  fixtures/reddit.py
  open_discussions/features.py
  open_discussions/permissions.py
  open_discussions/permissions_test.py
Labels: Waiting on Author

#632 Remove email_optin logic (#631)
  notifications/api.py
  notifications/api_test.py
Labels: Waiting on Author

#621 Handle anonymous users for comments
  cassettes/channels.views.comments_test.test_create_comment_anonymous[False].json
  cassettes/channels.views.comments_test.test_create_comment_anonymous[True].json
  cassettes/channels.views.comments_test.test_delete_comment_anonymous[False].json
  cassettes/channels.views.comments_test.test_delete_comment_anonymous[True].json
  cassettes/channels.views.comments_test.test_get_comment_anonymous[False].json
  cassettes/channels.views.comments_test.test_get_comment_anonymous[True].json
  cassettes/channels.views.comments_test.test_list_comments_anonymous[False].json
  cassettes/channels.views.comments_test.test_list_comments_anonymous[True].json
  cassettes/channels.views.comments_test.test_more_comments_anonymous[False].json
  cassettes/channels.views.comments_test.test_more_comments_anonymous[True].json
  cassettes/channels.views.comments_test.test_update_comment_anonymous[False].json
  cassettes/channels.views.comments_test.test_update_comment_anonymous[True].json
  channels/utils.py
  channels/views/comments.py
  channels/views/comments_test.py
  factory_data/channels.views.comments_test.test_get_comment_anonymous[False].json
  factory_data/channels.views.comments_test.test_get_comment_anonymous[True].json
  factory_data/channels.views.comments_test.test_list_comments_anonymous[False].json
  factory_data/channels.views.comments_test.test_list_comments_anonymous[True].json
  factory_data/channels.views.comments_test.test_more_comments_anonymous[False].json
  factory_data/channels.views.comments_test.test_more_comments_anonymous[True].json
Labels: Needs Review

#635 Fixed race condition with NotificationSettings trigger_frequency
  notifications/notifiers/email.py
  notifications/notifiers/email_test.py
Labels: Waiting on Author

#624 add embed.ly proxy API
  embedly/__init__.py
  embedly/admin.py
  embedly/api.py
  embedly/api_test.py
  embedly/apps.py
  embedly/migrations/__init__.py
  embedly/models.py
  embedly/urls.py
  embedly/views.py
  embedly/views_test.py
  open_discussions/settings.py
  open_discussions/urls.py
  static/js/lib/api.js
  static/js/lib/api_test.js
Labels: Waiting on Author

#628 Handle anonymous access for frontpage and posts
  cassettes/channels.views.frontpage_test.test_frontpage_anonymous[False].json
  cassettes/channels.views.frontpage_test.test_frontpage_anonymous[True].json
  cassettes/channels.views.posts_test.test_create_post_anonymous[False].json
  cassettes/channels.views.posts_test.test_create_post_anonymous[True].json
  cassettes/channels.views.posts_test.test_delete_post_anonymous[False].json
  cassettes/channels.views.posts_test.test_delete_post_anonymous[True].json
  cassettes/channels.views.posts_test.test_get_post_anonymous[False].json
  cassettes/channels.views.posts_test.test_get_post_anonymous[True].json
  cassettes/channels.views.posts_test.test_list_posts_anonymous[False].json
  cassettes/channels.views.posts_test.test_list_posts_anonymous[True].json
  cassettes/channels.views.posts_test.test_update_post_anonymous[False].json
  cassettes/channels.views.posts_test.test_update_post_anonymous[True].json
  channels/utils.py
  channels/views/frontpage.py
  channels/views/frontpage_test.py
  channels/views/posts.py
  channels/views/posts_test.py
  factory_data/channels.views.frontpage_test.test_frontpage_anonymous[False].json
  factory_data/channels.views.frontpage_test.test_frontpage_anonymous[True].json
  factory_data/channels.views.posts_test.test_get_post_anonymous[False].json
  factory_data/channels.views.posts_test.test_get_post_anonymous[True].json
  factory_data/channels.views.posts_test.test_list_posts_anonymous[False].json
  factory_data/channels.views.posts_test.test_list_posts_anonymous[True].json
Labels: Waiting on Author

#627 Allow access for anonymous users to see moderator list
  cassettes/channels.views.contributors_test.test_add_contributor_anonymous[False].json
  cassettes/channels.views.contributors_test.test_add_contributor_anonymous[True].json
  cassettes/channels.views.contributors_test.test_detail_contributor_anonymous[False].json
  cassettes/channels.views.contributors_test.test_detail_contributor_anonymous[True].json
  cassettes/channels.views.contributors_test.test_list_contributors_anonymous[False].json
  cassettes/channels.views.contributors_test.test_list_contributors_anonymous[True].json
  cassettes/channels.views.contributors_test.test_remove_contributor_anonymous[False].json
  cassettes/channels.views.contributors_test.test_remove_contributor_anonymous[True].json
  cassettes/channels.views.moderators_test.test_add_moderator_anonymous[False].json
  cassettes/channels.views.moderators_test.test_add_moderator_anonymous[True].json
  cassettes/channels.views.moderators_test.test_list_moderators_anonymous[False].json
  cassettes/channels.views.moderators_test.test_list_moderators_anonymous[True].json
  cassettes/channels.views.moderators_test.test_remove_moderator_anonymous[False].json
  cassettes/channels.views.moderators_test.test_remove_moderator_anonymous[True].json
  cassettes/channels.views.reports_test.test_report_anonymous[False].json
  cassettes/channels.views.reports_test.test_report_anonymous[True].json
  cassettes/channels.views.subscribers_test.test_add_subscriber_anonymous[False].json
  cassettes/channels.views.subscribers_test.test_add_subscriber_anonymous[True].json
  cassettes/channels.views.subscribers_test.test_detail_subscriber_anonymous[False].json
  cassettes/channels.views.subscribers_test.test_detail_subscriber_anonymous[True].json
  cassettes/channels.views.subscribers_test.test_remove_subscriber_anonymous[False].json
  cassettes/channels.views.subscribers_test.test_remove_subscriber_anonymous[True].json
  channels/views/contributors_test.py
  channels/views/moderators.py
  channels/views/moderators_test.py
  channels/views/reports_test.py
  channels/views/subscribers_test.py
  factory_data/channels.views.moderators_test.test_list_moderators_anonymous[False].json
  factory_data/channels.views.moderators_test.test_list_moderators_anonymous[True].json
  factory_data/channels.views.reports_test.test_report_anonymous[False].json
  factory_data/channels.views.reports_test.test_report_anonymous[True].json
Labels: Waiting on Author

#645 Add empty search Django app and elasticsearch Docker container
  .env.example
  app.json
  docker-compose.travis.yml
  docker-compose.yml
  open_discussions/settings.py
  open_discussions/settings_test.py
  requirements.in
  requirements.txt
  search/__init__.py
  search/management/__init__.py
  search/management/commands/__init__.py
  search/management/commands/index_content.py
  tox.ini
Labels: Needs Review

#644 Added handling for praw errors in email notifications
  notifications/notifiers/comments.py
  notifications/utils.py
  notifications/utils_test.py
Labels: Waiting on Author

#652 Upgrade celery
  requirements.in
  requirements.txt
Labels: Waiting on Author
