Repository mitodl/open-discussions, pull requests merged in 2018-03, with the labels that each got.

#512 add report post links to the frontpage and channel page
  static/js/components/CompactPostDisplay.js
  static/js/components/CompactPostDisplay_test.js
  static/js/components/PostList.js
  static/js/components/PostList_test.js
  static/js/containers/ChannelPage.js
  static/js/containers/HomePage.js
  static/js/containers/PostPage.js
  static/js/containers/PostPage_test.js
  static/js/hoc/withPostModeration.js
  static/js/lib/reports.js
Labels: Work in Progress

#515 fix how we calculate loaded and notFound for the post page
  static/js/containers/PostPage.js
Labels: Waiting on Author

#504 Added weekly/daily frontpage tasks
  .env.example
  README.md
  app.json
  docker-compose.yml
  mail/api.py
  mail/templates/frontpage/body.html
  mail/templates/frontpage/body.txt
  mail/templates/frontpage/subject.txt
  notifications/api.py
  notifications/api_test.py
  notifications/factories.py
  notifications/migrations/0002_add_notifications.py
  notifications/models.py
  notifications/notifiers/__init__.py
  notifications/notifiers/base.py
  notifications/notifiers/base_test.py
  notifications/notifiers/email.py
  notifications/notifiers/email_test.py
  notifications/notifiers/exceptions.py
  notifications/notifiers/frontpage.py
  notifications/notifiers/frontpage_test.py
  notifications/tasks.py
  notifications/tasks_test.py
  notifications/utils.py
  notifications/utils_test.py
  open_discussions/features.py
  open_discussions/features_test.py
  open_discussions/settings.py
  open_discussions/settings_test.py
  open_discussions/test_utils.py
  open_discussions/test_utils_test.py
  open_discussions/urls.py
  open_discussions/utils.py
  open_discussions/utils_test.py
  open_discussions/views.py
  tox.ini
Labels: Blocked, Waiting on Author

#511 add email settings page
  open_discussions/urls.py
  static/js/containers/App.js
  static/js/containers/App_test.js
  static/js/containers/SettingsPage.js
  static/js/factories/settings.js
  static/js/factories/settings_test.js
  static/js/factories/util.js
  static/js/flow/settingsTypes.js
  static/js/lib/api.js
  static/js/lib/api_test.js
  static/js/lib/auth.js
  static/js/lib/auth_test.js
  static/js/lib/redux_rest.js
  static/js/lib/url.js
  static/js/reducers/settings.js
  static/scss/layout.scss
  static/scss/settings.scss
Labels: Waiting on Author

#516 Track user activity
  .env.example
  README.md
  open_discussions/middleware/__init__.py
  open_discussions/middleware/feature_flags.py
  open_discussions/middleware/feature_flags_test.py
  open_discussions/middleware/user_activity.py
  open_discussions/middleware/user_activity_test.py
  open_discussions/middleware_test.py
  open_discussions/settings.py
  open_discussions/settings_test.py
  profiles/migrations/0004_add_last_active_on.py
  profiles/models.py
  test_requirements.txt
  tox.ini
Labels: Waiting on Author

#524 add profile picture and name of user to UI
  open_discussions/views.py
  open_discussions/views_test.py
  static/js/components/Navigation.js
  static/js/components/Navigation_test.js
  static/js/components/UserInfo.js
  static/js/components/UserInfo_test.js
  static/js/flow/declarations.js
  static/scss/_variables.scss
  static/scss/layout.scss
  static/scss/navigation.scss
  static/scss/user-info.scss
Labels: Waiting on Author

#519 Fix travis errors
  Procfile
  docker-compose.travis.yml
  docker-compose.yml
Labels: Waiting on Author

#526 Fixed celery log levels with sentry
  .env.example
  app.json
  open_discussions/celery.py
  open_discussions/settings.py
Labels: Waiting on Author

#530 Upgrade Django to 1.11, other upgrades
  conftest.py
  open_discussions/templatetags/render_bundle.py
  open_discussions/urls.py
  pytest.ini
  requirements.in
  requirements.txt
Labels: Needs Review

#527 Add response mail template and implement for frontpage digests
  mail/api.py
  mail/api_test.py
  mail/templates/email_base.html
  mail/templates/frontpage/body.html
  mail/templates/frontpage/body.txt
  mail/templates/frontpage/subject.txt
  mail/templates/sample/body.html
  mail/templates/sample/body.txt
  mail/templatetags/__init__.py
  mail/templatetags/timeago.py
  notifications/notifiers/frontpage.py
  notifications/notifiers/frontpage_test.py
  open_discussions/authentication.py
  open_discussions/authentication_test.py
  open_discussions/settings.py
  open_discussions/urls.py
  requirements.in
  requirements.txt
  static/images/mit-logo.jpg
Labels: Waiting on Author

#537 Added model and API to subscribe to comments and posts
  cassettes/channels.views.comments_test.test_list_comments_none.json
  cassettes/channels.views.comments_test.test_update_comment_subscribe.json
  cassettes/channels.views.comments_test.test_update_comment_unsubscribe.json
  cassettes/channels.views.posts_test.test_list_posts_none.json
  cassettes/channels.views.posts_test.test_subscribe_post[False-False-0-1].json
  cassettes/channels.views.posts_test.test_subscribe_post[False-True-1-2].json
  cassettes/channels.views.posts_test.test_subscribe_post[True-False-1-1].json
  cassettes/channels.views.posts_test.test_subscribe_post[True-True-2-2].json
  cassettes/channels.views.posts_test.test_unsubscribe_post.json
  channels/api.py
  channels/api_test.py
  channels/migrations/0002_add_subscription.py
  channels/models.py
  channels/serializers.py
  channels/test_constants.py
  channels/utils.py
  channels/utils_test.py
  channels/views/comments.py
  channels/views/comments_test.py
  channels/views/frontpage.py
  channels/views/frontpage_test.py
  channels/views/posts.py
  channels/views/posts_test.py
  channels/views/reports.py
  channels/views/reports_test.py
  factory_data/channels.views.comments_test.test_list_comments_none.json
  factory_data/channels.views.comments_test.test_update_comment_subscribe.json
  factory_data/channels.views.comments_test.test_update_comment_unsubscribe.json
  factory_data/channels.views.posts_test.test_list_posts_none.json
  factory_data/channels.views.posts_test.test_subscribe_post[False-False-0-1].json
  factory_data/channels.views.posts_test.test_subscribe_post[False-True-1-2].json
  factory_data/channels.views.posts_test.test_subscribe_post[True-False-1-1].json
  factory_data/channels.views.posts_test.test_subscribe_post[True-True-2-2].json
  factory_data/channels.views.posts_test.test_unsubscribe_post.json
  requirements.in
  requirements.txt
Labels: Waiting on Author

#540 Fixed query error on populate command
  notifications/management/commands/populate_notification_settings.py
Labels: Waiting on Author

#550 Fixed issue with request KeyError on email send
  channels/serializers.py
  channels/views/frontpage.py
  channels/views/posts.py
  channels/views/reports.py
  notifications/notifiers/frontpage.py
  notifications/notifiers/frontpage_test.py
Labels: Waiting on Author

#533 Added email tasks to crontab
  open_discussions/settings.py
Labels: Waiting on Author

#554 fix settings page
  static/js/containers/App_test.js
  static/js/containers/SettingsPage.js
  static/js/containers/SettingsPage_test.js
  static/js/factories/settings.js
  static/js/factories/settings_test.js
  static/js/reducers/settings.js
Labels: Waiting on Author

#575 add remove post link to channel view
  static/js/components/PostList.js
  static/js/components/PostList_test.js
  static/js/containers/ChannelPage.js
Labels: Waiting on Author

#574 Fixes some layout issues with the email template
  mail/templates/email_base.html
  mail/templates/frontpage/body.html
Labels: Waiting on Author

#578 Several small changes to email digest
  mail/templates/email_base.html
  mail/templates/frontpage/body.html
  mail/templates/frontpage/subject.txt
Labels: Waiting on Author
