Repository mitodl/open-discussions, pull requests merged in 2018-10, with the labels that each got.

#1233 Updated email templates and added mail debugger
  fixtures/common.py
  mail/api.py
  mail/api_test.py
  mail/forms.py
  mail/templates/comments/body.html
  mail/templates/comments/subject.txt
  mail/templates/email_base.html
  mail/templates/email_debugger.html
  mail/templates/frontpage/body.html
  mail/templates/password_reset/body.html
  mail/templates/sample/body.html
  mail/templates/verification/body.html
  mail/templates/verification/subject.txt
  mail/urls.py
  mail/views.py
  notifications/notifiers/frontpage_test.py
  open_discussions/urls.py
  open_discussions/views.py
  open_discussions/views_test.py
  requirements.in
  requirements.txt
  sites/api.py
  sites/api_test.py
  static/images/MIT_circle_red.jpg
  static/images/MIT_circle_red.svg
Labels: Needs Review

#1272 tweaks to channel appearance form page
  static/js/components/admin/EditChannelAppearanceForm.js
  static/js/containers/ChannelBanner.js
  static/scss/admin.scss
  static/scss/channel-banner.scss
  static/scss/channel.scss
  static/scss/profile-image.scss
Labels: Needs Review

#1280 fix author line display on post card
  static/js/components/ExpandedPostDisplay.js
  static/js/components/ExpandedPostDisplay_test.js
  static/scss/_breakpoints.scss
  static/scss/post.scss
Labels: Waiting on Author

#1251 Removed JWT logic and made login url conditional on email auth flag
  static/js/lib/fetch_auth.js
  static/js/lib/fetch_auth_test.js
Labels: Waiting on Author

#1283 update remove post dialog to better match behavior
  static/js/hoc/withPostModeration.js
Labels: Waiting on Author

#1262 Add support for the next param for login/register
  authentication/serializers.py
  authentication/utils.py
  authentication/views_test.py
  open_discussions/settings.py
  static/js/containers/auth/AuthRequiredPage.js
  static/js/containers/auth/AuthRequiredPage_test.js
  static/js/containers/auth/LoginPage.js
  static/js/containers/auth/LoginPage_test.js
  static/js/containers/auth/RegisterPage.js
  static/js/containers/auth/RegisterPage_test.js
  static/js/flow/authTypes.js
  static/js/lib/api.js
  static/js/lib/auth.js
  static/js/lib/fetch_auth.js
  static/js/lib/fetch_auth_test.js
  static/js/lib/url.js
  static/js/lib/url_test.js
  static/js/reducers/auth.js
Labels: Work in Progress

#1285 Replace percent with viewport dimensions
  static/js/components/Embedly.js
  static/js/components/Loading.js
Labels: Needs Review

#1279 Replace underscores with dashes in post slugs
  channels/utils.py
  channels/utils_test.py
  channels/views/posts_test.py
  open_discussions/urls.py
  static/js/containers/PostPage.js
  static/js/containers/PostPage_test.js
  static/js/lib/url_test.js
Labels: Waiting on Author

#1298 Refactored form update logic on post creation page
  static/js/containers/CreatePostPage.js
  static/js/containers/CreatePostPage_test.js
  static/js/lib/util.js
  static/js/lib/validation.js
Labels: Needs Review

#1288 Added support for next param
  authentication/serializers.py
  authentication/utils.py
  authentication/views_test.py
  open_discussions/settings.py
  static/js/containers/auth/AuthRequiredPage.js
  static/js/containers/auth/AuthRequiredPage_test.js
  static/js/containers/auth/LoginPage.js
  static/js/containers/auth/LoginPage_test.js
  static/js/containers/auth/RegisterPage.js
  static/js/containers/auth/RegisterPage_test.js
  static/js/flow/authTypes.js
  static/js/lib/api.js
  static/js/lib/auth.js
  static/js/lib/auth_test.js
  static/js/lib/fetch_auth.js
  static/js/lib/fetch_auth_test.js
  static/js/lib/url.js
  static/js/lib/url_test.js
  static/js/reducers/auth.js
Labels: Waiting on Author

#1297 fix styling for channel members tab
  static/js/components/Dialog.js
  static/js/components/admin/EditChannelMembersForm.js
  static/js/components/admin/MembersList.js
  static/js/components/admin/MembersList_test.js
  static/js/containers/admin/EditChannelContributorsPage.js
  static/js/containers/admin/EditChannelContributorsPage_test.js
  static/js/containers/admin/EditChannelMembershipPage.js
  static/js/containers/admin/EditChannelModeratorsPage.js
  static/js/containers/admin/EditChannelModeratorsPage_test.js
  static/scss/admin.scss
  static/scss/button.scss
  static/scss/form.scss
  static/scss/layout.scss
  static/scss/link.scss
Labels: Waiting on Author

#1304 Bumped django version
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1295 Updated login tooltip prompt for anon users
  static/js/components/CommentForms.js
  static/js/components/CommentVoteForm.js
  static/js/components/FollowButton.js
  static/js/components/LoginPopup.js
  static/js/components/LoginPopup_test.js
  static/js/components/PostUpvoteButton.js
  static/js/components/ReplyButton.js
  static/js/components/SharePopup.js
  static/js/lib/util.js
  static/scss/_variables.scss
  static/scss/popup.scss
Labels: Needs Review

#1311 Fixed anonymous user signup prompt for post upvote button
  static/js/components/PostUpvoteButton.js
  static/scss/popup.scss
Labels: Waiting on Author

#1307 move the channel edit button to channel banner
  static/js/components/SubscriptionsList.js
  static/js/components/SubscriptionsList_test.js
  static/js/containers/ChannelBanner.js
  static/js/containers/ChannelBanner_test.js
  static/js/containers/ChannelPage.js
  static/scss/channel-banner.scss
  static/scss/channel.scss
Labels: Waiting on Author

#1308 fix styling of thumbnail and URL icon
  static/scss/post-list.scss
Labels: Waiting on Author

#1320 Fixed the --name arg to the set_channel_allow_top command
  channels/management/commands/set_channel_allow_top.py
Labels: Waiting on Author

#1312 Added login popup/tooltip to drawer compose button
  static/js/components/LoginPopup.js
  static/js/components/Navigation.js
  static/js/components/Navigation_test.js
  static/js/containers/Drawer.js
  static/js/containers/Drawer_test.js
  static/js/factories/util.js
  static/scss/drawer.scss
  static/scss/popup.scss
Labels: Waiting on Author

#1318 try out using Storybook for component development
  hot-reload-dev-server.js
  package.json
  static/js/storybook/addons.js
  static/js/storybook/config.js
  static/js/storybook/index.js
  static/js/storybook/webpack.config.js
  webpack.config.dev.js
  yarn.lock
Labels: Waiting on Author

#1303 Shorten menu options
  static/js/components/CommentRemovalForm.js
  static/js/components/CommentTree.js
  static/js/components/CommentTree_test.js
  static/js/components/CompactPostDisplay.js
  static/js/components/CompactPostDisplay_test.js
  static/js/components/ExpandedPostDisplay.js
  static/js/components/UserMenu.js
Labels: Waiting on Author

#1315 Channel-specific analytics should trigger on direct URL load
  static/js/hoc/withChannelTracker.js
  static/js/hoc/withChannelTracker_test.js
Labels: Needs Review

#1322 Fixes the dialog buttons submitting the form
  static/js/components/Dialog.js
Labels: Waiting on Author

#1330 add moment as a dependency
  package.json
  yarn.lock
Labels: Waiting on Author

#1268 Added home page intro cards for logged in and anonymous users
  static/js/containers/HomePage.js
  static/js/containers/HomePage_test.js
  static/js/lib/ui.js
  static/scss/home-page.scss
  static/scss/layout.scss
Labels: Needs Review

#1338 change the message shown in the image upload dialog box
  static/js/components/ImageUploaderForm.js
Labels: Needs Review

#1334 link and button styling changes
  static/js/components/CompactPostDisplay.js
  static/js/components/CreatePostForm.js
  static/js/components/admin/MembersList.js
  static/js/storybook/index.js
  static/scss/button.scss
  static/scss/create-post.scss
  static/scss/link.scss
Labels: Needs Review

#1323 upgrade react, react-dom to latest
  package.json
  static/js/components/UserMenu_test.js
  static/js/containers/PostPage_test.js
  yarn.lock
Labels: Waiting on Author

#1343 make the button on the image uploader form have type="button"
  static/js/components/ImageUploaderForm.js
Labels: Waiting on Author

#1339 fix spacing for top of channel loading component
  static/js/components/Loading.js
  static/scss/channel.scss
Labels: Waiting on Author

#1346 Third pass of email templates
  channels/serializers.py
  channels/views/frontpage_test.py
  channels/views/posts_test.py
  channels/views/reports_test.py
  channels/views/test_utils.py
  mail/api.py
  mail/api_test.py
  mail/templates/comments/body.html
  mail/templates/email_base.html
  mail/templates/frontpage/body.html
  mail/templates/frontpage/subject.txt
  mail/templates/password_reset/body.html
  mail/templates/verification/body.html
  mail/views.py
  notifications/notifiers/comments_test.py
  notifications/notifiers/email_test.py
  notifications/notifiers/frontpage_test.py
Labels: Waiting on Author

#1340 Hide useless asteroid warnings when running tests
  authentication/pipeline/user.py
  channels/api_test.py
  channels/serializers.py
  open_discussions/settings_test.py
  pylintrc
  search/indexing_api.py
  search/task_helpers.py
  test_requirements.txt
Labels: Waiting on Author

#1348 Added a screenshots section to PR template
  pull_request_template.md
Labels: Waiting on Author

#1341 Split posts and comments into separate Elasticsearch indices
  search/connection.py
  search/constants.py
  search/indexing_api.py
  search/indexing_api_test.py
  search/serializers.py
  search/serializers_test.py
  search/task_helpers.py
  search/task_helpers_test.py
  search/tasks.py
  search/tasks_test.py
Labels: Waiting on Author

#1362 PR template: add checkbox for mobile screenshots
  pull_request_template.md
Labels: Waiting on Author

#1355 'Open Discussions' -> 'Open Learning'
  static/js/containers/App.js
  static/js/containers/PostPage.js
  static/js/hoc/withPostModeration.js
  static/js/lib/title.js
  static/js/lib/title_test.js
Labels: Waiting on Author

#1372 fix styling of intro card on mobile
  static/scss/home-page.scss
Labels: Waiting on Author

#1375 fix post form validation for URL validity
  static/js/components/CreatePostForm.js
  static/js/lib/validation.js
  static/js/lib/validation_test.js
Labels: Waiting on Author

#1371 Added fixes for email template font issues
  authentication/views.py
  mail/templates/comments/body.html
  mail/templates/frontpage/body.html
  mail/templates/password_reset/body.html
  mail/templates/verification/body.html
Labels: Waiting on Author

#1377 Add REST API for search
  open_discussions/features.py
  open_discussions/urls.py
  search/api.py
  search/api_test.py
  search/urls.py
  search/views.py
  search/views_test.py
Labels: Waiting on Author

#1382 Fixed template context for email confirmation emails
  mail/api.py
  mail/api_test.py
  mail/verification_api.py
  mail/verification_api_test.py
  notifications/notifiers/email.py
Labels: Waiting on Author

#1351 Channel design updates
  static/js/containers/ChannelAvatar.js
  static/js/containers/ChannelAvatar_test.js
  static/js/containers/ChannelBanner.js
  static/js/containers/ChannelBanner_test.js
  static/js/containers/ChannelPage.js
  static/js/containers/HomePage.js
  static/js/lib/util.js
  static/js/lib/util_test.js
  static/scss/_variables.scss
  static/scss/channel-banner.scss
  static/scss/channel.scss
  static/scss/drawer.scss
  static/scss/post-list.scss
Labels: Waiting on Author

#1376 Fix registration for MM-only accounts
  authentication/serializers.py
  authentication/utils.py
  authentication/views_test.py
  cassettes/authentication.views_test.test_login_register_flows[register_mm_exists].json
  factory_data/authentication.views_test.test_login_register_flows[register_mm_exists].json
  static/js/containers/auth/LoginPage.js
  static/js/flow/authTypes.js
  static/js/lib/api.js
  static/js/lib/auth.js
  static/js/lib/auth_test.js
Labels: Waiting on Author

#1390 Revert "Added hover highlight on post card"
  static/scss/post.scss
Labels: Waiting on Author

#1383 add new link style, put it on post-title
  static/js/components/CompactPostDisplay.js
  static/js/storybook/index.js
  static/scss/link.scss
Labels: Waiting on Author

#1394 Fix placement of reported comment dropdown
  static/js/components/CommentTree.js
  static/scss/comment.scss
Labels: Waiting on Author

#1406 Allow link type posts to be pinned
  static/js/components/CompactPostDisplay.js
Labels: Waiting on Author

#1395 Fixed signup page UI issues
  package.json
  static/js/components/auth/AuthEmailForm.js
  static/scss/auth.scss
  yarn.lock
Labels: Needs Review

#1407 Hid channel avatar on mobile
  static/scss/channel.scss
Labels: Waiting on Author

#1373 Index user profiles in Elasticsearch
  fixtures/users.py
  profiles/models.py
  profiles/serializers.py
  profiles/serializers_test.py
  search/api.py
  search/constants.py
  search/indexing_api.py
  search/indexing_api_test.py
  search/serializers.py
  search/serializers_test.py
  search/task_helpers.py
  search/task_helpers_test.py
  search/tasks.py
  search/tasks_test.py
Labels: Waiting on Author

#1412 Add `post_slug` to post and comment docs in Elasticsearch index
  fixtures/reddit.py
  search/indexing_api.py
  search/serializers.py
  search/serializers_test.py
Labels: Waiting on Author

#1416 Always align sort menu to the right
  static/scss/post-list.scss
Labels: Needs Review

#1424 Fix login page button label
  static/js/components/auth/AuthEmailForm.js
  static/js/containers/auth/RegisterPage.js
Labels: Needs Review

#1428 Use iterator when retrieving profiles
  search/serializers.py
Labels: Waiting on Author

#1433 Refactor channel header
  static/js/components/ChannelHeader.js
  static/js/components/ChannelHeader_test.js
  static/js/components/SortPicker.js
  static/js/components/SortPicker_test.js
  static/js/containers/ChannelPage.js
  static/js/storybook/index.js
  static/scss/channel.scss
  static/scss/post-list.scss
Labels: Waiting on Author

#1432 Enabled newrelic for our workers
  Procfile
Labels: Waiting on Author

#1409 Add indexing user as first moderator to every channel if not already a moderator
  cassettes/channels.views.channels_test.test_create_channel.json
  cassettes/channels.views.channels_test.test_create_channel_already_exists.json
  cassettes/channels.views.channels_test.test_create_channel_no_descriptions.json
  cassettes/channels.views.channels_test.test_create_channel_noauth.json
  cassettes/channels.views.channels_test.test_create_channel_nonstaff.json
  channels/factories.py
  channels/management/commands/add_index_user_to_channels.py
  channels/serializers.py
  channels/serializers_test.py
  channels/views/channels_test.py
  factory_data/channels.views.channels_test.test_create_channel.json
  factory_data/channels.views.channels_test.test_create_channel_already_exists.json
  factory_data/channels.views.channels_test.test_create_channel_no_descriptions.json
  factory_data/channels.views.channels_test.test_create_channel_noauth.json
  factory_data/channels.views.channels_test.test_create_channel_nonstaff.json
  fixtures/reddit.py
  fixtures/users.py
  profiles/serializers_test.py
Labels: Waiting on Author

#1435 Split profiles into chunks for indexing
  .env.example
  app.json
  search/indexing_api.py
  search/indexing_api_test.py
  search/serializers.py
  search/serializers_test.py
  search/tasks.py
  search/tasks_test.py
Labels: Needs Review

#1437 Add search textbox component
  static/js/components/SearchTextbox.js
  static/js/components/SearchTextbox_test.js
  static/js/storybook/index.js
  static/scss/form.scss
  static/scss/layout.scss
  static/scss/search.scss
Labels: Needs Review
