Repository mitodl/open-discussions, pull requests merged in 2019-02, with the labels that each got.

#1794 upgrade react to @latest
  package.json
  yarn.lock
Labels: Waiting on Author

#1788 add about field to channel model
  cassettes/channels.views.channels_test.test_patch_channel_about.json
  channels/factories/models.py
  channels/migrations/0019_channel_about.py
  channels/models.py
  channels/proxies.py
  channels/serializers/channels.py
  channels/serializers/channels_test.py
  channels/views/channels_test.py
  channels/views/test_utils.py
  factory_data/channels.views.channels_test.test_patch_channel_about.json
Labels: Waiting on Author

#1795 Add validation to widget configuration inputs, fix URL validation
  static/js/components/EmbedlyCard.js
  static/js/components/EmbedlyCard_test.js
  static/js/components/widgets/MarkdownWidget_test.js
  static/js/components/widgets/RssWidget_test.js
  static/js/components/widgets/UrlWidget_test.js
  static/js/components/widgets/WidgetEditDialog.js
  static/js/components/widgets/WidgetEditDialog_test.js
  static/js/components/widgets/WidgetField.js
  static/js/components/widgets/WidgetField_test.js
  static/js/factories/widgets.js
  static/js/factories/widgets_test.js
  static/js/lib/constants.js
  static/js/lib/embed.js
  static/js/lib/util.js
  static/js/lib/util_test.js
  static/js/lib/validation.js
  static/js/lib/validation_test.js
  static/js/lib/widgets.js
  static/js/lib/widgets_test.js
  static/js/storybook/index.js
  widgets/factories.py
  widgets/serializers/widget_list.py
  widgets/serializers/widget_list_test.py
Labels: Waiting on Author

#1799 Switched backpopulate_posts to a more reliable submission fetch
  channels/tasks.py
  channels/tasks_test.py
Labels: Waiting on Author

#1808 Fixed exception with lazy submissions
  channels/tasks.py
  channels/tasks_test.py
Labels: Waiting on Author

#1790 Fixed contributor delete permissions and changed logic for showing leave channel option
  channels/views/contributors.py
  channels/views/contributors_test.py
  open_discussions/permissions.py
  open_discussions/permissions_test.py
  static/js/components/ChannelHeader.js
  static/js/components/ChannelHeader_test.js
  static/js/containers/ChannelFollowControls.js
  static/js/containers/ChannelFollowControls_test.js
Labels: Waiting on Author

#1797 Show related posts on the post detail page
  app.json
  open_discussions/features.py
  open_discussions/settings.py
  open_discussions/views.py
  open_discussions/views_test.py
  search/api.py
  search/api_test.py
  search/constants.py
  search/indexing_api.py
  search/indexing_api_test.py
  search/urls.py
  search/views.py
  search/views_test.py
  static/js/containers/ChannelPage.js
  static/js/containers/PostDetailSidebar.js
  static/js/containers/PostDetailSidebar_test.js
  static/js/containers/PostPage.js
  static/js/factories/channels.js
  static/js/flow/declarations.js
  static/js/global_init.js
  static/js/hoc/withSidebar.js
  static/js/lib/api/api.js
  static/js/lib/api/api_test.js
  static/js/lib/redux_rest.js
  static/js/reducers/related_posts.js
  static/js/reducers/related_posts_test.js
  static/scss/_variables.scss
  static/scss/layout.scss
  static/scss/related.scss
Labels: Waiting on Author

#1815 fix the thing
  static/scss/close-button.scss
Labels: Waiting on Author

#1816 Fix link menu when editing rich text widget
  static/js/components/Editor.js
  static/js/components/Editor_test.js
  static/scss/add-link-menu.scss
Labels: Needs Review

#1813 Switch backpopulate over to the list() api
  channels/backpopulate_api.py
  channels/backpopulate_api_test.py
Labels: Waiting on Author

#1822 upgrade to react 16.8
  package.json
  static/js/components/widgets/RssWidget.js
  yarn.lock
Labels: Waiting on Author

#1818 Fixed bug with preview text for posts including a base64-encoded image
  static/js/components/CompactPostDisplay.js
  static/js/components/CompactPostDisplay_test.js
  static/js/components/TruncatedText.js
  static/js/components/TruncatedText_test.js
  static/js/lib/posts.js
  static/js/lib/posts_test.js
Labels: Waiting on Author

#1819 Bumped Elasticsearch docker image version to 6.5.4
  docker-compose.yml
Labels: Waiting on Author

#1825 Removed EMAIL_AUTH flag
  authentication/views.py
  authentication/views_test.py
  open_discussions/features.py
  open_discussions/views.py
  open_discussions/views_test.py
  static/js/components/UserMenu.js
  static/js/components/UserMenu_test.js
  static/js/flow/declarations.js
  static/js/global_init.js
  static/js/lib/api/fetch_auth.js
  static/js/lib/api/fetch_auth_test.js
Labels: Waiting on Author

#1823 Added reporting of validation errors to sentry
  open_discussions/exceptions.py
  open_discussions/exceptions_test.py
Labels: Waiting on Author

#1753 Copy mitodl/course_catalog app into discussions
  app.json
  course_catalog/__init__.py
  course_catalog/constants.py
  course_catalog/factories.py
  course_catalog/management/__init__.py
  course_catalog/management/commands/__init__.py
  course_catalog/management/commands/backpopulate_edx_data.py
  course_catalog/management/commands/backpopulate_ocw_data.py
  course_catalog/migrations/0001_initial.py
  course_catalog/migrations/0002_creating_models_20181221_1825.py
  course_catalog/migrations/0003_add_related_name_20190108_2355.py
  course_catalog/migrations/0004_make_short_description_nullable_20190110_2018.py
  course_catalog/migrations/0005_course_last_modified.py
  course_catalog/migrations/0006_adds_timestampedmodel_20190111_0031.py
  course_catalog/migrations/0007_alters_created_on_field_20190111_1755.py
  course_catalog/migrations/0008_renames_last_updated_field_20190111_1820.py
  course_catalog/migrations/0009_alter_course_price_digits_20190114_1807.py
  course_catalog/migrations/0010_make_fields_nullable_20190114_1947.py
  course_catalog/migrations/0011_increases_max_length_for_short_description_20190116_1942.py
  course_catalog/migrations/0012_changes_short_description_to_text_field_20190116_2046.py
  course_catalog/migrations/0013_increases_max_length_for_semester_20190117_1627.py
  course_catalog/migrations/0014_course_featured.py
  course_catalog/migrations/0015_increases_image_src_max_length_20190129_1812.py
  course_catalog/migrations/0016_adds_course_published_field.py
  course_catalog/migrations/0017_adds_is_resource_to_course.py
  course_catalog/migrations/0018_changes_is_resource_field_20190131_2152.py
  course_catalog/migrations/__init__.py
  course_catalog/models.py
  course_catalog/serializers.py
  course_catalog/serializers_test.py
  course_catalog/task_helpers.py
  course_catalog/task_helpers_test.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  course_catalog/urls.py
  course_catalog/views.py
  open_discussions/settings.py
  open_discussions/urls.py
  requirements.in
  requirements.txt
  search/tasks.py
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/1.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/10.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/11.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/12.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/13.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/14.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/15.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/16.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/2.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/3.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/4.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/5.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/6.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/7.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/8.json
  test_json/PROD/9/9.15/Fall_2007/9-15-biochemistry-and-pharmacology-of-synaptic-transmission-fall-2007/0/9.json
  test_json/test_mitx_course.json
  test_requirements.txt
Labels: Waiting on Author

#1826 Changed article thumbnail rendering to serve from embedly
  README.md
  channels/api.py
  channels/migrations/0015_add_article_cover_image.py
  channels/migrations/0020_remove_article_thumbnail.py
  channels/models.py
  channels/serializers/posts.py
  channels/utils.py
  channels/views/posts_test.py
  profiles/utils.py
  profiles/utils_test.py
  static/js/components/CompactPostDisplay.js
  static/js/components/CompactPostDisplay_test.js
  static/js/lib/posts.js
  static/js/lib/posts_test.js
  static/scss/post.scss
Labels: Waiting on Author

#1827 Remove usages of channel description and allow_widget_ui
  open_discussions/features.py
  open_discussions/views.py
  open_discussions/views_test.py
  static/js/components/ChannelSidebar.js
  static/js/components/ChannelSidebar_test.js
  static/js/components/admin/CreateChannelForm.js
  static/js/components/admin/CreateChannelForm_test.js
  static/js/components/admin/EditChannelBasicForm.js
  static/js/components/admin/EditChannelBasicForm_test.js
  static/js/containers/ChannelPage_test.js
  static/js/containers/ChannelSettingsLink.js
  static/js/containers/ChannelSettingsLink_test.js
  static/js/containers/PostPage_test.js
  static/js/containers/admin/EditChannelAppearancePage_test.js
  static/js/containers/admin/EditChannelBasicPage.js
  static/js/containers/admin/EditChannelBasicPage_test.js
  static/js/containers/admin/EditChannelModeratorsPage_test.js
  static/js/factories/channels.js
  static/js/factories/channels_test.js
  static/js/factories/widgets.js
  static/js/flow/declarations.js
  static/js/flow/discussionTypes.js
  static/js/global_init.js
  static/js/lib/api/channels.js
  static/js/lib/api/channels_test.js
  static/js/lib/channels.js
  static/js/lib/channels_test.js
Labels: Waiting on Author

#1830 Added a few issue templates
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/rfc_template.md
  .github/pull_request_template.md
  docs/rfcs/0000-template.md
Labels: Work in Progress

#1783 Reindex posts and comments from DB
  channels/management/commands/backpopulate_missing_posts.py
  channels/models.py
  open_discussions/test_utils.py
  open_discussions/utils.py
  open_discussions/utils_test.py
  search/indexing_api.py
  search/indexing_api_test.py
  search/serializers.py
  search/serializers_test.py
  search/task_helpers.py
  search/task_helpers_test.py
  search/tasks.py
  search/tasks_test.py
Labels: Waiting on Author

#1721 Create and update course documents in Elasticsearch
  course_catalog/conftest.py
  course_catalog/signals.py
  course_catalog/signals_test.py
  course_catalog/task_helpers.py
  course_catalog/task_helpers_test.py
  course_catalog/tasks_test.py
  search/api.py
  search/constants.py
  search/indexing_api.py
  search/indexing_api_test.py
  search/serializers.py
  search/serializers_test.py
  search/task_helpers.py
  search/task_helpers_test.py
  search/tasks.py
  search/tasks_test.py
Labels: Waiting on Author

#1835 RFC: Caching system for third party data
  docs/rfcs/0001-caching-system.md
Labels: Needs Review, RFC

#1839 New setting to specify if only course images should be uploaded
  app.json
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  open_discussions/settings.py
Labels: Waiting on Author

#1848 Remove automatic focus from dialog radio buttons
  static/js/components/widgets/WidgetEditDialog.js
  static/js/components/widgets/WidgetEditDialog_test.js
Labels: Needs Review

#1857 Created docker container config for running the app in a Jupyter notebook
  Dockerfile-nb
  README.md
  app.ipynb.example
  docker-compose-notebook.yml
Labels: Waiting on Author

#1803 People widget
  package.json
  static/js/components/SearchTextbox.js
  static/js/components/SearchTextbox_test.js
  static/js/components/widgets/DragHandle.js
  static/js/components/widgets/PeopleItem.js
  static/js/components/widgets/PeopleItem_test.js
  static/js/components/widgets/PeopleList.js
  static/js/components/widgets/PeopleList_test.js
  static/js/components/widgets/PeopleSelector.js
  static/js/components/widgets/PeopleSelector_test.js
  static/js/components/widgets/PeopleWidget.js
  static/js/components/widgets/PeopleWidget_test.js
  static/js/components/widgets/WidgetEditDialog.js
  static/js/components/widgets/WidgetEditDialog_test.js
  static/js/components/widgets/WidgetField.js
  static/js/components/widgets/WidgetField_test.js
  static/js/components/widgets/WidgetInstance.js
  static/js/components/widgets/WidgetInstance_test.js
  static/js/components/widgets/WidgetList_test.js
  static/js/containers/widgets/WidgetListContainer.js
  static/js/containers/widgets/WidgetListContainer_test.js
  static/js/factories/search.js
  static/js/factories/widgets.js
  static/js/flow/widgetTypes.js
  static/js/lib/constants.js
  static/js/lib/widgets.js
  static/js/storybook/index.js
  static/scss/_variables.scss
  static/scss/layout.scss
  static/scss/widget.scss
  widgets/factories.py
  widgets/serializers/people.py
  widgets/serializers/people_test.py
  widgets/serializers/react_fields.py
  widgets/serializers/rss.py
  widgets/serializers/utils.py
  widgets/views_test.py
  yarn.lock
Labels: Waiting on Author

#1846 RFC: Embedly link preview indexing
  docs/rfcs/0002-indexing-embedly-link-preview.md
Labels: Needs Review, RFC

#1854 Limit widget dialog focus to widget type selection
  static/js/components/widgets/WidgetEditDialog.js
  static/js/components/widgets/WidgetEditDialog_test.js
Labels: Needs Review

#1851 Add url to Course model and helper method to determine its value
  app.json
  course_catalog/migrations/0019_course_url.py
  course_catalog/models.py
  course_catalog/task_helpers.py
  course_catalog/task_helpers_test.py
  course_catalog/tasks_test.py
  open_discussions/settings.py
  test_json/test_mitx_course01.json
  test_json/test_mitx_course02.json
Labels: Waiting on Author

#1853 scroll validations errors into view on post create page
  static/js/components/ScrollToTop_test.js
  static/js/containers/CreatePostPage.js
  static/js/containers/CreatePostPage_test.js
  static/js/containers/admin/EditChannelBasicPage_test.js
  static/js/containers/admin/EditChannelContributorsPage_test.js
  static/js/containers/admin/EditChannelModeratorsPage_test.js
Labels: Waiting on Author

#1844 add channel about page frontend
  static/js/components/ChannelHeader.js
  static/js/components/ChannelHeader_test.js
  static/js/components/ChannelNavbar.js
  static/js/components/ChannelNavbar_test.js
  static/js/containers/App.js
  static/js/containers/App_test.js
  static/js/containers/ChannelAboutPage.js
  static/js/containers/ChannelAboutPage_test.js
  static/js/containers/ChannelPage.js
  static/js/containers/ChannelPage_test.js
  static/js/containers/ChannelRouter.js
  static/js/containers/PostPage.js
  static/js/containers/PostPage_test.js
  static/js/containers/SearchPage.js
  static/js/containers/SearchPage_test.js
  static/js/containers/admin/EditChannelAppearancePage.js
  static/js/containers/admin/EditChannelAppearancePage_test.js
  static/js/containers/admin/EditChannelBasicPage.js
  static/js/factories/channels.js
  static/js/flow/discussionTypes.js
  static/js/hoc/withChannelHeader.js
  static/js/hoc/withCommentModeration.js
  static/js/hoc/withPostModeration.js
  static/js/lib/api/channels.js
  static/js/lib/channels.js
  static/js/lib/routing.js
  static/js/lib/url.js
  static/js/lib/util.js
  static/js/util/form_actions.js
  static/js/util/integration_test_helper.js
Labels: Needs Review

#1864 Fix tests
  static/js/components/ChannelNavbar_test.js
  static/js/components/widgets/WidgetEditDialog_test.js
Labels: Needs Review

#1852 add validation to post edit form
  static/js/components/CommentForms.js
  static/js/components/CommentForms_test.js
  static/js/components/CreatePostForm.js
  static/js/components/CreatePostForm_test.js
  static/js/containers/CreatePostPage.js
  static/js/containers/CreatePostPage_test.js
  static/js/flow/discussionTypes.js
  static/js/lib/api/posts.js
  static/js/lib/posts.js
  static/js/lib/posts_test.js
  static/js/lib/validation.js
  static/js/lib/validation_test.js
Labels: Waiting on Author

#1862 Readme updates
  README.md
Labels: Waiting on Author

#1858 Updates ocw-data-parser version to fix large file memory issue with uploading large files to S3 in course_catalog
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1784 Course search UI
  open_discussions/features.py
  open_discussions/urls.py
  open_discussions/views.py
  open_discussions/views_test.py
  search/api.py
  search/api_test.py
  static/js/components/CompactCourseDisplay.js
  static/js/components/CompactCourseDisplay_test.js
  static/js/components/Loading.js
  static/js/components/SearchResult.js
  static/js/components/SearchResult_test.js
  static/js/containers/App.js
  static/js/containers/CourseSearchPage.js
  static/js/containers/CourseSearchPage_test.js
  static/js/factories/courses.js
  static/js/factories/search.js
  static/js/flow/declarations.js
  static/js/flow/discussionTypes.js
  static/js/flow/searchTypes.js
  static/js/global_init.js
  static/js/lib/api/api.js
  static/js/lib/api/api_test.js
  static/js/lib/constants.js
  static/js/lib/courses.js
  static/js/lib/courses_test.js
  static/js/lib/picker.js
  static/js/lib/redux_rest.js
  static/js/lib/search.js
  static/js/lib/search_test.js
  static/js/lib/util.js
  static/js/reducers/courses.js
  static/js/reducers/courses_test.js
  static/scss/course.scss
  static/scss/layout.scss
  static/scss/search.scss
Labels: Waiting on Author

#1860 Cache RSS widget feed data
  Procfile
  docker-compose.yml
  open_discussions/settings.py
  open_discussions/test_utils.py
  open_discussions/test_utils_test.py
  requirements.in
  requirements.txt
  scripts/heroku-release-phase.sh
  widgets/serializers/rss.py
  widgets/serializers/rss_test.py
Labels: Waiting on Author

#1867 Fixed anonymous create post page bug
  static/js/components/auth/PrivateRoute.js
  static/js/components/auth/PrivateRoute_test.js
  static/js/containers/App.js
  static/js/lib/api/fetch_auth.js
  static/js/lib/api/fetch_auth_test.js
  static/js/lib/auth.js
  static/js/lib/auth_test.js
Labels: Needs Review

#1859 Adds functionality to export edx courses into json format and upload it to s3
  course_catalog/management/commands/backpopulate_edx_data.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  open_discussions/settings.py
Labels: Waiting on Author

#1855 Added embedly link preview content to index
  channels/api.py
  channels/api_test.py
  channels/migrations/0021_post_preview_text.py
  channels/models.py
  channels/proxies.py
  channels/serializers/posts.py
  channels/serializers/posts_test.py
  channels/utils.py
  channels/views/posts_test.py
  embedly/api.py
  embedly/api_test.py
  embedly/views.py
  embedly/views_test.py
  open_discussions/settings.py
  search/indexing_api.py
  search/indexing_api_test.py
  search/task_helpers.py
  search/task_helpers_test.py
  search/tasks.py
  search/tasks_test.py
Labels: Waiting on Author

#1868 Remove TODO comments
  static/js/containers/CourseSearchPage.js
  static/js/containers/SearchPage.js
Labels: Needs Review

#1873 fix article validation
  static/js/lib/validation.js
  static/js/lib/validation_test.js
Labels: Needs Review

#1881 Bumped ocw-data-parser version
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1872 Added opengraph metadata tags for social sharing
  open_discussions/templates/base.html
  open_discussions/templates/social.html
  open_discussions/views.py
  open_discussions/views_test.py
  static/images/mit-dome.jpg
Labels: Waiting on Author

#1875 Fix comment dialog dialog bug and refactor PostPage_test
  static/js/containers/PostPage.js
  static/js/containers/PostPage_test.js
Labels: Waiting on Author

#1882 update the channel post listing after pinning / unpinning a post
  static/js/hoc/withPostList.js
  static/js/hoc/withPostList_test.js
Labels: Waiting on Author

#1880 add livestream widget to home page
  livestream/__init__.py
  livestream/api.py
  livestream/api_test.py
  livestream/apps.py
  livestream/urls.py
  livestream/views.py
  livestream/views_test.py
  open_discussions/features.py
  open_discussions/settings.py
  open_discussions/urls.py
  open_discussions/views.py
  open_discussions/views_test.py
  static/js/components/LiveStream.js
  static/js/components/LiveStream_test.js
  static/js/containers/App_test.js
  static/js/containers/CreatePostPage_test.js
  static/js/containers/HomePage.js
  static/js/containers/HomePage_test.js
  static/js/containers/ProfileEditPage_test.js
  static/js/factories/livestream.js
  static/js/flow/declarations.js
  static/js/flow/livestreamTypes.js
  static/js/global_init.js
  static/js/hoc/withSidebar.js
  static/js/lib/api/livestream.js
  static/js/lib/embed.js
  static/js/lib/redux_rest.js
  static/js/reducers/livestream.js
  static/js/util/integration_test_helper.js
Labels: Waiting on Author

#1878 Hide embedly title for embedly widgets
  static/js/components/EmbedlyCard.js
  static/js/components/widgets/UrlWidget.js
  static/js/lib/embed.js
  static/js/lib/embed_test.js
Labels: Needs Review

#1884 try out not using docker for JS tests on travis
  .travis.yml
  travis/Dockerfile-travis-watch
  travis/Dockerfile-travis-watch-build
  travis/js_tests.sh
  travis/update-docker-hub.sh
Labels: Waiting on Author
