Repository mitodl/open-discussions, pull requests merged in 2019-10, with the labels that each got.

#2251 Open drawer for programs
  course_catalog/serializers.py
  course_catalog/serializers_test.py
  package.json
  static/js/components/ExpandedLearningResourceDisplay.js
  static/js/components/ExpandedLearningResourceDisplay_test.js
  static/js/components/LearningResourceCard.js
  static/js/components/LearningResourceCard_test.js
  static/js/components/LearningResourceDrawer.js
  static/js/components/LearningResourceDrawer_test.js
  static/js/factories/learning_resources.js
  static/js/flow/discussionTypes.js
  static/js/lib/learning_resources.js
  static/js/lib/learning_resources_test.js
  static/js/lib/queries/programs.js
  static/js/lib/queries/user_lists.js
  static/js/lib/util.js
  static/js/lib/util_test.js
  static/scss/course.scss
  static/scss/profile-image.scss
  yarn.lock
Labels: Waiting on Author

#2262 Fix an intermittent test failure
  search/serializers.py
Labels: Waiting on Author

#2250 course search mobile view
  static/js/components/CourseFilterDrawer.js
  static/js/components/CourseFilterDrawer_test.js
  static/js/components/CourseSearchbox.js
  static/js/components/CourseSearchbox_test.js
  static/js/components/PageBanner.js
  static/js/components/ResponsiveWrapper.js
  static/js/components/ResponsiveWrapper_test.js
  static/js/components/SearchFacet.js
  static/js/components/SearchFacet_test.js
  static/js/hooks/util.js
  static/js/lib/constants.js
  static/js/pages/CourseIndexPage.js
  static/js/pages/CourseSearchPage.js
  static/js/util/integration_test_helper.js
  static/scss/button.scss
  static/scss/course-filter-drawer.scss
  static/scss/course-searchbox.scss
  static/scss/course.scss
  static/scss/layout.scss
  static/scss/learning-resource-card.scss
  static/scss/search.scss
Labels: Waiting on Author

#2270 refactor the tooltips!
  package.json
  static/js/components/CommentForm.js
  static/js/components/CommentForm_test.js
  static/js/components/CommentTree.js
  static/js/components/CommentTree_test.js
  static/js/components/CommentVoteForm.js
  static/js/components/CommentVoteForm_test.js
  static/js/components/Drawer.js
  static/js/components/Drawer_test.js
  static/js/components/ExpandedPostDisplay.js
  static/js/components/ExpandedPostDisplay_test.js
  static/js/components/FollowButton.js
  static/js/components/FollowButton_test.js
  static/js/components/LearningResourceCard.js
  static/js/components/LoginPopup.js
  static/js/components/LoginPopup_test.js
  static/js/components/LoginTooltip.js
  static/js/components/LoginTooltip_test.js
  static/js/components/Navigation.js
  static/js/components/Navigation_test.js
  static/js/components/PostUpvoteButton.js
  static/js/components/PostUpvoteButton_test.js
  static/js/components/ReplyButton.js
  static/js/components/ReplyButton_test.js
  static/js/components/ShareTooltip.js
  static/js/components/ShareTooltip_test.js
  static/js/lib/comments.js
  static/js/lib/comments_test.js
  static/js/pages/PostPage.js
  static/scss/layout.scss
  static/scss/popup.scss
  static/scss/post.scss
  static/scss/tooltip.scss
  yarn.lock
Labels: Waiting on Author

#2247 Refactor MITx integration to new etl pipeline
  app.json
  conftest.py
  course_catalog/api.py
  course_catalog/api_test.py
  course_catalog/conftest.py
  course_catalog/etl/conftest.py
  course_catalog/etl/constants.py
  course_catalog/etl/loaders.py
  course_catalog/etl/loaders_test.py
  course_catalog/etl/micromasters.py
  course_catalog/etl/micromasters_test.py
  course_catalog/etl/mitx.py
  course_catalog/etl/mitx_test.py
  course_catalog/etl/ocw.py
  course_catalog/etl/ocw_test.py
  course_catalog/etl/openedx.py
  course_catalog/etl/openedx_test.py
  course_catalog/etl/pipelines.py
  course_catalog/etl/pipelines_test.py
  course_catalog/etl/utils.py
  course_catalog/etl/utils_test.py
  course_catalog/etl/xpro.py
  course_catalog/management/commands/backpopulate_edx_data.py
  course_catalog/serializers.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  fixtures/aws.py
  open_discussions/settings.py
  test_json/test_mitx_course.json
  test_json/test_mitx_course02.json
  test_json/test_non_mitx_course.json
Labels: Waiting on Author

#2268 fix a layout bug introduced in 2250
  static/js/components/PageBanner.js
  static/scss/course-searchbox.scss
Labels: Waiting on Author

#2260 Remove OCW courses from search if they are unpublished
  course_catalog/api.py
  course_catalog/api_test.py
  course_catalog/serializers.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
Labels: Waiting on Author

#2265 Rename CourseRun to LearningResourceRun
  RELEASE.rst
  course_catalog/admin.py
  course_catalog/api.py
  course_catalog/api_test.py
  course_catalog/etl/loaders.py
  course_catalog/etl/loaders_test.py
  course_catalog/etl/openedx.py
  course_catalog/etl/openedx_test.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/factories.py
  course_catalog/migrations/0041_rename_course_run.py
  course_catalog/migrations/0042_rename_run_id.py
  course_catalog/models.py
  course_catalog/serializers.py
  course_catalog/serializers_test.py
  course_catalog/views.py
  course_catalog/views_test.py
  search/indexing_api.py
  search/serializers.py
  search/serializers_test.py
  static/js/components/ExpandedLearningResourceDisplay.js
  static/js/components/ExpandedLearningResourceDisplay_test.js
  static/js/components/LearningResourceCard.js
  static/js/components/LearningResourceCard_test.js
  static/js/components/NewCoursesWidget.js
  static/js/components/NewCoursesWidget_test.js
  static/js/factories/learning_resources.js
  static/js/factories/search.js
  static/js/flow/discussionTypes.js
  static/js/flow/searchTypes.js
  static/js/lib/learning_resources.js
  static/js/lib/learning_resources_test.js
  static/js/lib/search.js
  static/js/lib/search_test.js
  test_json/xpro_programs.json
Labels: Waiting on Author

#2267 Create one run per program
  course_catalog/etl/loaders.py
  course_catalog/etl/loaders_test.py
  course_catalog/etl/micromasters.py
  course_catalog/etl/micromasters_test.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/factories.py
  course_catalog/migrations/0043_runs_for_programs.py
  course_catalog/models.py
  course_catalog/serializers.py
  course_catalog/serializers_test.py
  search/indexing_api.py
  search/serializers.py
  search/serializers_test.py
  static/js/components/ExpandedLearningResourceDisplay.js
  static/js/components/ExpandedLearningResourceDisplay_test.js
  static/js/components/SearchResult_test.js
  static/js/factories/learning_resources.js
  static/js/factories/search.js
  static/js/flow/discussionTypes.js
  static/js/lib/search_test.js
Labels: Waiting on Author

#2272 Add Open Learning Library Import
  app.json
  course_catalog/api.py
  course_catalog/api_test.py
  course_catalog/constants.py
  course_catalog/etl/conftest.py
  course_catalog/etl/loaders.py
  course_catalog/etl/loaders_test.py
  course_catalog/etl/micromasters.py
  course_catalog/etl/micromasters_test.py
  course_catalog/etl/mitx.py
  course_catalog/etl/oll.py
  course_catalog/etl/oll_test.py
  course_catalog/etl/openedx.py
  course_catalog/etl/openedx_test.py
  course_catalog/etl/pipelines.py
  course_catalog/etl/pipelines_test.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/factories.py
  course_catalog/management/commands/backpopulate_oll_data.py
  course_catalog/migrations/0044_uniq_by_platform_id.py
  course_catalog/models.py
  course_catalog/serializers.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  open_discussions/settings.py
  search/api.py
  search/serializers.py
  search/serializers_test.py
  search/task_helpers.py
  search/task_helpers_test.py
  test_json/test_oll_courses.json
Labels: Waiting on Author

#2280 Add import pipeline for xPro non-program courses
  app.json
  course_catalog/etl/pipelines.py
  course_catalog/etl/pipelines_test.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/management/commands/backpopulate_xpro_data.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  open_discussions/settings.py
  test_json/xpro_courses.json
Labels: Waiting on Author

#2282 Add instructors, topics, and program prices to micromasters ETL transform
  course_catalog/etl/micromasters.py
  course_catalog/etl/micromasters_test.py
Labels: Waiting on Author

#2279 Import xPro program topics and instructors
  course_catalog/admin.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/models.py
  static/js/components/ExpandedLearningResourceDisplay.js
  static/js/components/ExpandedLearningResourceDisplay_test.js
  static/js/lib/learning_resources.js
  static/js/lib/learning_resources_test.js
  static/js/lib/search.js
  test_json/xpro_programs.json
Labels: Waiting on Author

#2288 only show/hide course search facet options when there are a lot of them
  static/js/components/SearchFacet.js
  static/js/components/SearchFacet_test.js
Labels: Waiting on Author

#2291 Prevent embedly from creating animated thumbnails
  static/js/lib/url.js
  static/js/lib/url_test.js
Labels: Waiting on Author

#2286 fix learning resource details drawer right-to-left behavior
  package.json
  static/js/components/Dialog.js
  static/js/components/Dialog_test.js
  static/js/components/Drawer.js
  static/js/components/Drawer_test.js
  static/js/components/ExpandedLearningResourceDisplay.js
  static/js/components/ExpandedLearningResourceDisplay_test.js
  static/js/components/LearningResourceDrawer.js
  static/js/components/Picker.js
  static/js/components/ProfileImage_test.js
  static/js/components/TruncatedText.js
  static/js/components/TruncatedText_test.js
  static/js/components/admin/EditChannelBasicForm.js
  static/js/pages/SettingsPage.js
  static/js/pages/SettingsPage_test.js
  static/scss/drawer.scss
  static/scss/layout.scss
  static/scss/truncated-text.scss
  static/scss/widget.scss
  yarn.lock
Labels: Waiting on Author

#2290 apply text style on hover to facet options
  static/scss/search.scss
Labels: Waiting on Author

#2295 Don't show any results if no text matches are found
  static/js/lib/search.js
  static/js/lib/search_test.js
Labels: Needs Review

#2296 Add support for multiple Offered By
  course_catalog/admin.py
  course_catalog/api.py
  course_catalog/api_test.py
  course_catalog/etl/loaders.py
  course_catalog/etl/loaders_test.py
  course_catalog/etl/micromasters.py
  course_catalog/etl/micromasters_test.py
  course_catalog/etl/openedx.py
  course_catalog/etl/openedx_test.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/factories.py
  course_catalog/management/commands/backpopulate_micromasters_data.py
  course_catalog/migrations/0045_deprecated_offered_by.py
  course_catalog/migrations/0046_add_learning_resource_offeror.py
  course_catalog/models.py
  course_catalog/serializers.py
  search/serializers.py
  search/serializers_test.py
  static/js/components/ExpandedLearningResourceDisplay.js
  static/js/components/ExpandedLearningResourceDisplay_test.js
  static/js/components/LearningResourceCard.js
  static/js/components/LearningResourceCard_test.js
  static/js/factories/learning_resources.js
  static/js/factories/search.js
  static/js/flow/discussionTypes.js
  static/js/flow/searchTypes.js
  static/js/lib/constants.js
  static/js/lib/learning_resources.js
  static/js/lib/learning_resources_test.js
  static/js/lib/search.js
  static/js/lib/search_test.js
Labels: Waiting on Author

#2299 fix a bug with the Cell component
  static/js/components/Grid.js
Labels: Work in Progress

#2319 Fix caniuse-lite breaking build by upgrading it
  .travis.yml
  Dockerfile-node
  package.json
  yarn.lock
Labels: Waiting on Author

#2316 Added VideoResource model
  course_catalog/constants.py
  course_catalog/factories.py
  course_catalog/migrations/0047_add_video_resource.py
  course_catalog/models.py
Labels: Needs Review

#2315 hide empty facets
  static/js/components/SearchFacet.js
  static/js/components/SearchFacet_test.js
Labels: Waiting on Author

#2323 add list view page
  static/js/Router.js
  static/js/components/CourseToolbar.js
  static/js/components/UserListCard.js
  static/js/components/UserListCard_test.js
  static/js/components/UserMenu.js
  static/js/lib/queries/user_lists.js
  static/js/lib/queries/user_lists_test.js
  static/js/lib/redux-query.js
  static/js/lib/redux_query.js
  static/js/lib/test_utils.js
  static/js/lib/url.js
  static/js/pages/App.js
  static/js/pages/CourseIndexPage_test.js
  static/js/pages/UserListPage.js
  static/js/pages/UserListPage_test.js
  static/js/store/configureStore.js
  static/js/util/integration_test_helper.js
  static/scss/button.scss
  static/scss/course.scss
  static/scss/layout.scss
  static/scss/user-list-card.scss
Labels: Waiting on Author

#2326 Allow CRUD operations for UserLists via API
  course_catalog/factories.py
  course_catalog/migrations/0048_privacy_default.py
  course_catalog/models.py
  course_catalog/permissions.py
  course_catalog/permissions_test.py
  course_catalog/serializers.py
  course_catalog/serializers_test.py
  course_catalog/views.py
  course_catalog/views_test.py
Labels: Needs Review

#2329 Differentiate between user lists and learning paths in the search index
  course_catalog/constants.py
  course_catalog/factories.py
  search/api.py
  search/api_test.py
  search/constants.py
  search/indexing_api.py
  search/serializers.py
  search/serializers_test.py
  static/js/factories/learning_resources.js
  static/js/flow/discussionTypes.js
  static/js/lib/constants.js
  static/js/lib/learning_resources.js
  static/js/lib/learning_resources_test.js
  static/js/pages/CourseSearchPage_test.js
Labels: Waiting on Author

#2327 Added VideoResource indexing
  course_catalog/factories.py
  search/api.py
  search/api_test.py
  search/constants.py
  search/indexing_api.py
  search/indexing_api_test.py
  search/serializers.py
  search/serializers_test.py
  search/task_helpers.py
  search/task_helpers_test.py
  search/tasks.py
  search/tasks_test.py
  static/js/factories/learning_resources.js
  static/js/factories/search.js
  static/js/flow/discussionTypes.js
  static/js/lib/constants.js
  static/js/lib/search_test.js
Labels: Waiting on Author

#2336 Added loader code for videos
  course_catalog/etl/loaders.py
  course_catalog/etl/loaders_test.py
Labels: Waiting on Author

#2337 Added video favoriting functionality
  course_catalog/etl/loaders.py
  course_catalog/etl/loaders_test.py
  course_catalog/factories.py
  course_catalog/migrations/0049_rename_video_resource_to_video.py
  course_catalog/models.py
  course_catalog/serializers.py
  course_catalog/urls.py
  course_catalog/views.py
  course_catalog/views_test.py
  search/api.py
  search/indexing_api.py
  search/serializers.py
  search/serializers_test.py
  search/task_helpers.py
  search/task_helpers_test.py
  search/tasks.py
  search/tasks_test.py
  static/js/components/LearningResourceCard.js
  static/js/lib/queries/bootcamps.js
  static/js/lib/queries/bootcamps_test.js
  static/js/lib/queries/courses.js
  static/js/lib/queries/courses_test.js
  static/js/lib/queries/learning_resources.js
  static/js/lib/queries/programs.js
  static/js/lib/queries/programs_test.js
  static/js/lib/queries/user_lists.js
  static/js/lib/queries/user_lists_test.js
  static/js/lib/queries/videos.js
  static/js/lib/queries/videos_test.js
  static/js/lib/search.js
  static/js/lib/search_test.js
  static/js/lib/url.js
  static/js/pages/CourseIndexPage.js
  static/js/pages/CourseSearchPage.js
Labels: Waiting on Author

#2324 Extract function for course catalog youtube video etl
  .env.example
  app.json
  course_catalog/etl/youtube.py
  course_catalog/etl/youtube_test.py
  open_discussions/settings.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#2345 add UI for creating User Lists
  course_catalog/constants.py
  package.json
  static/js/components/CreateUserListDialog.js
  static/js/components/CreateUserListDialog_test.js
  static/js/components/NewCoursesWidget_test.js
  static/js/components/UserListCard.js
  static/js/lib/constants.js
  static/js/lib/queries/user_lists.js
  static/js/lib/queries/user_lists_test.js
  static/js/lib/test_utils.js
  static/js/lib/validation.js
  static/js/lib/validation_test.js
  static/js/pages/UserListPage.js
  static/js/pages/UserListPage_test.js
  static/scss/create-user-list-dialog.scss
  static/scss/layout.scss
  static/scss/user-list-page.scss
  yarn.lock
Labels: Waiting on Author

#2355 add pyyaml to requirements
  requirements.in
  requirements.txt
Labels: Waiting on Author

#2348 Video data transform
  course_catalog/etl/pipelines.py
  course_catalog/etl/pipelines_test.py
  course_catalog/etl/youtube.py
  course_catalog/etl/youtube_test.py
Labels: Waiting on Author

#2334 course search tweaks
  static/js/components/CourseSearchbox.js
  static/js/components/CourseSearchbox_test.js
  static/js/components/ExpandedLearningResourceDisplay.js
  static/js/components/ExpandedLearningResourceDisplay_test.js
  static/js/components/Grid.js
  static/js/components/LearningResourceCard.js
  static/js/components/LearningResourceCard_test.js
  static/js/components/LearningResourceDrawer.js
  static/js/components/LearningResourceDrawer_test.js
  static/js/factories/learning_resources.js
  static/js/hooks/util.js
  static/js/lib/learning_resources.js
  static/js/lib/learning_resources_test.js
  static/js/pages/CourseIndexPage.js
  static/scss/card.scss
  static/scss/learning-resource-card.scss
Labels: Waiting on Author

#2350 hide 'my lists' button in course navbar when the user is anonymous
  static/js/components/CourseToolbar.js
  static/js/components/CourseToolbar_test.js
Labels: Waiting on Author
