Repository mitodl/open-discussions, pull requests merged in 2019-04, with the labels that each got.

#1937 Addresses issue #1930
  course_catalog/task_helpers.py
  course_catalog/task_helpers_test.py
Labels: Waiting on Author

#1940 refresh post list after removing a post (from channel index page)
  static/js/containers/ChannelPage.js
  static/js/hoc/withPostModeration.js
Labels: Waiting on Author

#1936 add channel members page
  package.json
  static/js/components/widgets/PeopleItem.js
  static/js/components/widgets/PeopleList.js
  static/js/components/widgets/PeopleList_test.js
  static/js/components/widgets/PeopleSelector.js
  static/js/components/widgets/PeopleSelector_test.js
  static/js/components/widgets/PeopleWidget.js
  static/js/components/widgets/PeopleWidget_test.js
  static/js/components/widgets/WidgetField.js
  static/js/components/widgets/WidgetField_test.js
  static/js/containers/ChannelMembersPage.js
  static/js/containers/ChannelMembersPage_test.js
  static/js/containers/ChannelRouter.js
  static/js/containers/SearchPage.js
  static/js/containers/SearchPage_test.js
  static/js/containers/widgets/WidgetListContainer.js
  static/js/factories/widgets.js
  static/js/lib/constants.js
  static/js/lib/url.js
  static/js/reducers/search.js
  static/js/util/integration_test_helper.js
  static/scss/channel-member-page.scss
  static/scss/layout.scss
  static/scss/widget.scss
  widgets/factories.py
  widgets/serializers/people.py
  widgets/serializers/people_test.py
  widgets/serializers/react_fields.py
  widgets/views_test.py
  yarn.lock
Labels: Waiting on Author

#1944 Added a redirect rule to handle traffic to the lemelsonx subdomain
  config/nginx.conf
  config/nginx.conf.erb
Labels: DevOps, Needs Review

#1953 Added redirect for handling themove.mit.edu
  config/nginx.conf
  config/nginx.conf.erb
Labels: DevOps, Waiting on Author

#1959 hide 'manage widgets' button in settings dropdown on post page
  static/js/containers/ChannelSettingsLink.js
  static/js/containers/ChannelSettingsLink_test.js
Labels: Waiting on Author

#1962 Upgraded urllib3
  requirements.in
  requirements.txt
Labels: Needs Review

#1961 Revert "Added reporting of validation errors to sentry"
  open_discussions/exceptions.py
  open_discussions/exceptions_test.py
Labels: Needs Review

#1956 add sorting for the members page
  profiles/api.py
  profiles/api_test.py
  search/indexing_api.py
  search/serializers.py
  search/serializers_test.py
  static/js/components/Picker.js
  static/js/components/Picker_test.js
  static/js/containers/ChannelMembersPage.js
  static/js/containers/ChannelMembersPage_test.js
  static/js/flow/searchTypes.js
  static/js/lib/picker.js
  static/js/lib/search.js
  static/js/lib/search_test.js
  static/scss/channel-member-page.scss
Labels: Waiting on Author

#1964 Added test for app.json validity
  open_discussions/app_tests.py
Labels: Waiting on Author

#1968 fix a flaky one
  profiles/api_test.py
Labels: Waiting on Author

#1975 Updated command to populate user subscriptions to take a list of channels
  channels/management/commands/backpopulate_default_channel.py
  channels/management/commands/subscribe_all_users_to_channel.py
  channels/tasks.py
  channels/tasks_test.py
Labels: Needs Review

#1973 Zagaran/upload master json
  course_catalog/management/commands/upload_all_master_json.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1957 Repair posts if they don't appear in the hot posts list
  app.json
  channels/api.py
  channels/task_helpers.py
  channels/task_helpers_test.py
  channels/tasks.py
  channels/tasks_test.py
  channels/utils.py
  open_discussions/features.py
  open_discussions/settings.py
Labels: Waiting on Author

#1977 refactor desktop drawer to collapse instead of hiding itself
  static/js/actions/ui.js
  static/js/components/Navigation.js
  static/js/components/NavigationItem.js
  static/js/components/NavigationItem_test.js
  static/js/components/SubscriptionsList.js
  static/js/components/SubscriptionsList_test.js
  static/js/containers/Drawer.js
  static/js/containers/Drawer_test.js
  static/js/reducers/ui.js
  static/js/reducers/ui_test.js
  static/scss/_variables.scss
  static/scss/drawer.scss
  static/scss/layout.scss
Labels: Waiting on Author

#1987 Send courses in chunks for master json parsing
  app.json
  course_catalog/tasks.py
  open_discussions/settings.py
Labels: Needs Review
