Repository mitodl/open-discussions, pull requests merged in 2019-03, with the labels that each got.

#1866 Course detail view
  package.json
  static/images/mitx-logo.png
  static/images/ocw-logo.png
  static/js/actions/ui.js
  static/js/components/CompactCourseDisplay.js
  static/js/components/CompactCourseDisplay_test.js
  static/js/components/ExpandedCourseDisplay.js
  static/js/components/ExpandedCourseDisplay_test.js
  static/js/components/SearchResult.js
  static/js/components/SearchResult_test.js
  static/js/containers/CourseDrawer.js
  static/js/containers/CourseDrawer_test.js
  static/js/containers/CourseSearchPage.js
  static/js/containers/CourseSearchPage_test.js
  static/js/containers/Drawer.js
  static/js/factories/courses.js
  static/js/factories/search.js
  static/js/flow/discussionTypes.js
  static/js/flow/searchTypes.js
  static/js/lib/api/courses.js
  static/js/lib/api/courses_test.js
  static/js/lib/redux_rest.js
  static/js/lib/search.js
  static/js/lib/search_test.js
  static/js/lib/util.js
  static/js/reducers/courses.js
  static/js/reducers/ui.js
  static/scss/course.scss
  static/scss/drawer.scss
  yarn.lock
Labels: Needs Review

#1871 Add channel invitations
  authentication/pipeline/invite.py
  authentication/pipeline/invite_test.py
  authentication/views_test.py
  channels/admin.py
  channels/factories/models.py
  channels/migrations/0022_add_channel_invitation.py
  channels/models.py
  channels/serializers/invites.py
  channels/serializers/invites_test.py
  channels/tasks.py
  channels/tasks_test.py
  channels/urls.py
  channels/views/invites.py
  channels/views/invites_test.py
  mail/templates/invite/body.html
  mail/templates/invite/subject.txt
  open_discussions/permissions.py
  open_discussions/settings.py
  static/js/containers/admin/EditChannelContributorsPage.js
  static/js/containers/admin/EditChannelContributorsPage_test.js
  static/js/factories/channels.js
  static/js/factories/channels_test.js
  static/js/flow/discussionTypes.js
  static/js/lib/api/channels.js
  static/js/lib/api/channels_test.js
  static/js/lib/redux_rest.js
  static/js/reducers/channel_invitations.js
  static/js/reducers/channel_invitations_test.js
Labels: Waiting on Author

#1885 Search UI RFC
  docs/rfcs/0003-search-ui.md
Labels: Needs Review, RFC

#1892 Display all topics in CompactCourseDisplay, make clickable
  static/js/components/CompactCourseDisplay.js
  static/js/components/CompactCourseDisplay_test.js
  static/js/components/ExpandedCourseDisplay.js
  static/js/components/SearchResult.js
  static/js/containers/CourseSearchPage.js
  static/js/containers/CourseSearchPage_test.js
  static/scss/course.scss
Labels: Needs Review

#1891 RFC for enhanced search facets
  docs/rfcs/0004-enhanced-facets.md
Labels: Needs Review, RFC

#1900 adds new field `availability` to Course model
  course_catalog/constants.py
  course_catalog/factories.py
  course_catalog/migrations/0020_course_availability.py
  course_catalog/models.py
  course_catalog/task_helpers.py
  course_catalog/task_helpers_test.py
  search/indexing_api.py
  search/serializers.py
  search/serializers_test.py
Labels: Waiting on Author

#1903 Updated Python runtime version
  Dockerfile
  runtime.txt
  travis/Dockerfile-travis-web
Labels: Waiting on Author

#1907 Bump django version
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1905 upgrade a few dependencies
  package.json
  yarn.lock
Labels: Needs Review

#1911 Fix typo
  mail/templates/invite/body.html
Labels: Waiting on Author

#1912 fix article post UI sluggishness
  static/js/components/ArticleEditor.js
Labels: Waiting on Author

#1906 Search facet improvements
  static/js/actions/ui.js
  static/js/components/Loading.js
  static/js/components/SearchFacet.js
  static/js/components/SearchFacet_test.js
  static/js/containers/CourseSearchPage.js
  static/js/containers/CourseSearchPage_test.js
  static/js/factories/search.js
  static/js/flow/searchTypes.js
  static/js/lib/api/api.js
  static/js/lib/api/api_test.js
  static/js/lib/redux_rest.js
  static/js/lib/search.js
  static/js/lib/search_test.js
  static/js/reducers/courses.js
  static/js/reducers/courses_test.js
  static/js/reducers/search.js
  static/js/reducers/search_test.js
  static/js/reducers/ui.js
  static/js/reducers/ui_test.js
  static/js/util/integration_test_helper.js
  static/scss/course.scss
  static/scss/search.scss
Labels: Needs Review

#1920 Show min price instead of max price for courses
  static/js/components/CompactCourseDisplay.js
  static/js/components/CompactCourseDisplay_test.js
  static/js/components/ExpandedCourseDisplay.js
  static/js/lib/courses.js
  static/js/lib/courses_test.js
Labels: Needs Review

#1919 add course index page
  course_catalog/admin.py
  package.json
  static/js/components/Card.js
  static/js/components/Card_test.js
  static/js/components/CompactCourseDisplay.js
  static/js/components/CourseCarousel.js
  static/js/components/CourseCarousel_test.js
  static/js/components/CoverImageInput_test.js
  static/js/containers/App.js
  static/js/containers/CourseIndexPage.js
  static/js/containers/CourseIndexPage_test.js
  static/js/containers/CourseSearchPage.js
  static/js/entry/root.js
  static/js/factories/courses.js
  static/js/lib/api/courses.js
  static/js/lib/api/courses_test.js
  static/js/reducers/index.js
  static/js/store/configureStore.js
  static/scss/_variables.scss
  static/scss/button.scss
  static/scss/card.scss
  static/scss/course-carousel.scss
  static/scss/layout.scss
  yarn.lock
Labels: Waiting on Author

#1916 Buttons to clear facets
  static/js/components/SearchFilter.js
  static/js/components/SearchFilter_test.js
  static/js/containers/CourseSearchPage.js
  static/js/containers/CourseSearchPage_test.js
  static/js/flow/searchTypes.js
  static/scss/search.scss
Labels: Needs Review

#1922 Label course availability by model field instead of dates in UI
  static/js/components/CompactCourseDisplay.js
  static/js/components/CompactCourseDisplay_test.js
  static/js/components/CourseCarousel.js
  static/js/components/CourseCarousel_test.js
  static/js/containers/CourseSearchPage.js
  static/js/factories/courses.js
  static/js/factories/search.js
  static/js/flow/discussionTypes.js
  static/js/flow/searchTypes.js
  static/js/lib/constants.js
  static/js/lib/courses.js
  static/js/lib/courses_test.js
  static/js/lib/search.js
  static/js/lib/search_test.js
Labels: Needs Review

#1927 new / upcoming courses widget on home page
  static/js/components/CourseCarousel.js
  static/js/containers/App_test.js
  static/js/containers/CreatePostPage_test.js
  static/js/containers/HomePage.js
  static/js/containers/HomePage_test.js
  static/js/containers/LiveStream.js
  static/js/containers/LiveStream_test.js
  static/js/containers/NewCoursesWidget.js
  static/js/containers/NewCoursesWidget_test.js
  static/js/containers/ProfileEditPage_test.js
  static/js/lib/test_utils.js
  static/js/lib/util.js
  static/js/lib/util_test.js
  static/scss/layout.scss
  static/scss/new-course-widget.scss
Labels: Waiting on Author

#1928 Modify facet behavior within/between groups
  static/js/components/SearchFacet.js
  static/js/components/SearchFacet_test.js
  static/js/containers/CourseSearchPage.js
  static/js/containers/CourseSearchPage_test.js
  static/js/flow/searchTypes.js
  static/js/lib/search.js
Labels: Needs Review

#1934 add cover image to course index page
  static/js/components/ChannelHeader.js
  static/js/components/PageBanner.js
  static/js/components/SearchTextbox.js
  static/js/components/admin/EditChannelAppearanceForm.js
  static/js/containers/ChannelBanner.js
  static/js/containers/ChannelBanner_test.js
  static/js/containers/ChannelRouter.js
  static/js/containers/CourseIndexPage.js
  static/js/containers/CourseIndexPage_test.js
  static/js/containers/admin/EditChannelBasicPage_test.js
  static/js/hoc/withChannelHeader.js
  static/js/lib/url.js
  static/scss/admin.scss
  static/scss/channel-banner.scss
  static/scss/channel.scss
  static/scss/course-index-page.scss
  static/scss/layout.scss
  static/scss/search.scss
Labels: Waiting on Author
