Repository mitodl/open-discussions, pull requests merged in 2020-07, with the labels that each got.

#3011 refactor post comments to have separate comment component
  .flowconfig
  static/js/components/Comment.js
  static/js/components/CommentRemovalForm.js
  static/js/components/CommentReportDialog.js
  static/js/components/CommentTree.js
  static/js/components/CommentTree_test.js
  static/js/components/CommentVoteForm.js
  static/js/components/CommentVoteForm_test.js
  static/js/components/Comment_test.js
  static/js/components/ProfileContributionFeed.js
  static/js/components/ProfileContributionFeed_test.js
  static/js/hoc/withCommentModeration.js
  static/js/hooks/comments.js
  static/js/lib/validation.js
  static/js/pages/PostPage.js
  static/js/pages/PostPage_test.js
  static/js/pages/admin/ChannelModerationPage.js
  static/js/pages/admin/ChannelModerationPage_test.js
  static/js/util/integration_test_helper.js
  static/scss/comment.scss
Labels: Waiting on Author

#3023 remove runs from videos and podcasts
  course_catalog/etl/loaders.py
  course_catalog/etl/loaders_test.py
  course_catalog/etl/podcast.py
  course_catalog/etl/podcast_test.py
  course_catalog/etl/youtube.py
  course_catalog/etl/youtube_test.py
  course_catalog/migrations/0073_remove_runs_for_videos_and_podcasts.py
  course_catalog/models.py
  search/serializers.py
  search/serializers_test.py
Labels: Needs Review

#3032 fix isort version
  test_requirements.txt
Labels: Needs Review

#3021 fix podcast etl
  course_catalog/etl/loaders.py
  course_catalog/etl/loaders_test.py
  course_catalog/etl/podcast.py
  course_catalog/etl/podcast_test.py
  test_html/test_podcast.rss
Labels: Waiting on Author

#3029 fix micromasters loader bug
  course_catalog/etl/pipelines.py
  course_catalog/etl/pipelines_test.py
Labels: Waiting on Author

#3035 add link to podcast page to LR drawer
  static/js/components/ExpandedLearningResourceDisplay.js
  static/js/components/ExpandedLearningResourceDisplay_test.js
  static/scss/learning-resource-drawer.scss
  static/scss/podcasts.scss
Labels: Needs Review

#3015 ensure audio player is present on all `/learn` pages
  static/js/actions/audio.js
  static/js/components/AudioPlayer.js
  static/js/components/AudioPlayer_test.js
  static/js/hooks/audio_player.js
  static/js/pages/App.js
  static/js/pages/CourseSearchPage.js
  static/js/reducers/audio.js
  static/js/reducers/audio_test.js
  static/scss/audio-player.scss
Labels: Waiting on Author

#3037 small refactor: pull method on HomePage.js out as component
  static/js/components/IntroCard.js
  static/js/components/IntroCard_test.js
  static/js/pages/HomePage.js
  static/js/pages/HomePage_test.js
Labels: Waiting on Author

#3038 [refactor] consolidate post voting
  static/js/components/CompactPostDisplay.js
  static/js/components/CompactPostDisplay_test.js
  static/js/components/ExpandedPostDisplay.js
  static/js/components/ExpandedPostDisplay_test.js
  static/js/components/PostList.js
  static/js/components/PostList_test.js
  static/js/components/PostUpvoteButton.js
  static/js/components/PostUpvoteButton_test.js
  static/js/components/ProfileContributionFeed.js
  static/js/components/ProfileContributionFeed_test.js
  static/js/components/SearchResult.js
  static/js/hoc/withPostList.js
  static/js/hoc/withPostList_test.js
  static/js/pages/PostPage.js
  static/js/pages/SearchPage.js
  static/js/util/api_actions.js
  static/js/util/api_actions_test.js
Labels: Waiting on Author

#3051 Block certain emails during registration
  authentication/admin.py
  authentication/migrations/0001_initial.py
  authentication/models.py
  mail/migrations/__init__.py
  mail/verification_api.py
  mail/verification_api_test.py
Labels: Waiting on Author

#3050 fix issue where 'footer' in nav drawer was covered by audio player
  static/scss/drawer.scss
Labels: Waiting on Author

#3039 refactor expanded post display
  static/js/components/ExpandedPostDisplay.js
  static/js/components/ExpandedPostDisplay_test.js
Labels: Waiting on Author

#3063 Added spam checking to posts and comments (#3062)
  app.json
  channels/serializers/comments.py
  channels/serializers/posts.py
  channels/spam.py
  channels/spam_test.py
  channels/task_helpers.py
  channels/task_helpers_test.py
  channels/tasks.py
  channels/tasks_test.py
  channels/views/comments_test.py
  channels/views/posts_test.py
  docker-compose.yml
  fixtures/common.py
  open_discussions/settings.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#3057 fix a few issues with comment voting
  static/js/components/CommentVoteForm.js
  static/js/components/CommentVoteForm_test.js
  static/js/components/ProfileContributionFeed.js
  static/js/pages/PostPage.js
  static/js/reducers/comments.js
  static/js/reducers/comments_test.js
  static/js/util/rest.js
Labels: Waiting on Author, merge freeze

#3059 make learn pages tababble
  package.json
  static/js/components/AddToListDialog.js
  static/js/components/CourseSearchbox.js
  static/js/components/CourseSearchbox_test.js
  static/js/components/Dialog.js
  static/js/components/Grid.js
  static/js/components/LearningResourceCard.js
  static/js/components/UserListFormDialog.js
  static/js/components/UserListItems.js
  static/js/components/UserMenu.js
  static/js/components/search/CourseFilterDrawer.js
  static/js/components/search/FilterableSearchFacet.js
  static/js/components/search/SearchFacetItem.js
  static/js/components/search/SearchFilter.js
  static/js/pages/CourseSearchPage.js
  yarn.lock
Labels: Waiting on Author, merge freeze

#3066 add podcast subscribe URLs to podcast ETL stuff
  course_catalog/etl/podcast.py
  course_catalog/etl/podcast_test.py
  course_catalog/factories.py
  course_catalog/migrations/0074_add_podcast_subscribe_urls.py
  course_catalog/models.py
  course_catalog/serializers.py
  course_catalog/serializers_test.py
  search/serializers.py
  search/serializers_test.py
Labels: Waiting on Author

#3069 fix read more
  static/js/components/TruncatedText.js
  static/js/components/TruncatedText_test.js
Labels: Needs Review

#3076 Save spam check results
  channels/admin.py
  channels/migrations/0025_spamcheckresult.py
  channels/models.py
  channels/spam.py
  channels/spam_test.py
  channels/tasks.py
  channels/tasks_test.py
  open_discussions/utils.py
  open_discussions/utils_test.py
Labels: Waiting on Author

#3073 python and JS upgrades
  package.json
  requirements.in
  requirements.txt
  yarn.lock
Labels: Waiting on Author

#3061 fix another padding issue with the drawer
  static/scss/drawer.scss
Labels: Waiting on Author

#3075 add podcast subscribe link frontend
  static/images/apple_podcasts.png
  static/images/google_podcasts.png
  static/js/components/ExpandedLearningResourceDisplay.js
  static/js/components/PodcastSubscribeButton.js
  static/js/components/PodcastSubscribeButton_test.js
  static/js/factories/podcasts.js
  static/js/flow/podcastTypes.js
  static/scss/_variables.scss
  static/scss/learning-resource-drawer.scss
  static/scss/podcasts.scss
Labels: Waiting on Author

#3082 Blocked IP model and middleware
  authentication/admin.py
  authentication/decorators.py
  authentication/middleware.py
  authentication/middleware_test.py
  authentication/migrations/0002_blockediprange.py
  authentication/models.py
  authentication/models_test.py
  course_catalog/views.py
  open_discussions/settings.py
  search/views.py
Labels: Waiting on Author

#3081 Added server-side 404 page for posts
  cassettes/channels.views.posts_test.test_get_removed_post[None-404].json
  cassettes/channels.views.posts_test.test_get_removed_post[client_user1-404].json
  cassettes/channels.views.posts_test.test_get_removed_post[client_user2-200].json
  channels/proxies.py
  channels/views/posts.py
  channels/views/posts_test.py
  docker-compose.override.yml
  factory_data/channels.views.posts_test.test_get_removed_post[None-404].json
  factory_data/channels.views.posts_test.test_get_removed_post[client_user1-404].json
  factory_data/channels.views.posts_test.test_get_removed_post[client_user2-200].json
  open_discussions/templates/400.html
  open_discussions/templates/403.html
  open_discussions/templates/404.html
  open_discussions/templates/base.html
  open_discussions/templates/index.html
  open_discussions/templates/react.html
  open_discussions/templates/social.html
  open_discussions/urls.py
  open_discussions/urls_test.py
  open_discussions/views.py
  open_discussions/views_test.py
  profiles/views_test.py
Labels: Waiting on Author

#3083 Only spm check if the post or comment text changes
  channels/serializers/comments.py
  channels/serializers/posts.py
Labels: Needs Review

#3067 generate rss for all MIT podcast episodes
  course_catalog/etl/podcast.py
  course_catalog/etl/podcast_test.py
  course_catalog/factories.py
  course_catalog/migrations/0075_podcastepisode_rss.py
  course_catalog/models.py
  course_catalog/serializers.py
  course_catalog/urls.py
  course_catalog/views.py
  static/images/podcast_cover_art.png
  test_requirements.txt
Labels: Needs Review

#3092 add rss_url to podcast etl
  course_catalog/etl/podcast.py
  course_catalog/etl/podcast_test.py
  course_catalog/factories.py
  course_catalog/migrations/0076_podcast_rss_url.py
  course_catalog/models.py
  course_catalog/serializers.py
  course_catalog/serializers_test.py
  search/serializers.py
  search/serializers_test.py
Labels: Waiting on Author
