Repository mitodl/open-discussions, pull requests merged in 2020-09, with the labels that each got.

#3129 Mock debounce to try to fix flaky tests
  static/js/components/ArticleEditor.js
  static/js/components/auth/AuthEmailForm.js
  static/js/pages/CourseSearchPage.js
  static/js/pages/CourseSearchPage_test.js
  static/js/util/integration_test_helper.js
Labels: Waiting on Author

#3126 correct typo in "Mechanical Engineering"
  course_catalog/data/ucc-topic-mappings.csv
Labels: Waiting on Author

#3135 fix course search textbox behavior
  static/js/components/Grid.js
  static/js/components/SearchResult.js
  static/js/components/SearchResult_test.js
  static/js/components/search/CourseFilterDrawer.js
  static/js/hooks/learning_resources.js
  static/js/hooks/util.js
  static/js/pages/CourseSearchPage.js
  static/js/pages/CourseSearchPage_test.js
  static/js/util/integration_test_helper.js
Labels: Waiting on Author

#3137 Update ContentFile (Resource) ES doc structure
  course_catalog/api.py
  course_catalog/constants.py
  course_catalog/etl/ocw.py
  course_catalog/etl/ocw_test.py
  course_catalog/factories.py
  course_catalog/migrations/0077_learningresourcerun_slug.py
  course_catalog/models.py
  course_catalog/serializers.py
  search/indexing_api.py
  search/serializers.py
  search/serializers_test.py
Labels: Waiting on Author

#3147 Add accessibility links to footers
  static/js/components/Footer.js
  static/js/components/PodcastFooter.js
  static/scss/drawer.scss
Labels: Waiting on Author

#3141 add level and department to search
  course_catalog/etl/ocw.py
  course_catalog/migrations/0078_course_department.py
  course_catalog/models.py
  course_catalog/serializers.py
  search/indexing_api.py
  search/serializers.py
  search/serializers_test.py
Labels: Waiting on Author

#3150 add post and comment information to spam check admin
  channels/admin.py
Labels: Waiting on Author

#3149 Fields for determining OCW URLs
  course_catalog/constants.py
  course_catalog/etl/ocw.py
  course_catalog/etl/ocw_test.py
  course_catalog/factories.py
  course_catalog/migrations/0079_ocw_slugs.py
  course_catalog/models.py
  course_catalog/serializers.py
  course_catalog/serializers_test.py
  search/indexing_api.py
  search/serializers.py
  search/serializers_test.py
Labels: Needs Review

#3151 Don't sync an OCW course if it's in the NON_COURSE_DIRECTORIES list
  course_catalog/api.py
  course_catalog/api_test.py
  course_catalog/management/commands/delete_non_courses.py
Labels: Waiting on Author

#3163 fix spam check admin
  channels/admin.py
Labels: Waiting on Author

#3162 use latest version of ocw-data-parser
  requirements.in
  requirements.txt
Labels: Waiting on Author

#3154 Youtube video resource RFC
  docs/rfcs/0005-video-resources.md
Labels: RFC, Waiting on Author

#3145 Upgrade pillow to 7.2.0
  requirements.in
  requirements.txt
Labels: Waiting on Author

#3153 add spam management commands
  channels/factories/models.py
  channels/management/commands/reclassify_spam.py
  channels/spam.py
  channels/tasks.py
  channels/tasks_test.py
Labels: Waiting on Author

#3159 Add embedded youtube videos as course resources
  course_catalog/etl/ocw.py
  course_catalog/etl/ocw_test.py
  course_catalog/etl/utils.py
  course_catalog/etl/utils_test.py
  course_catalog/factories.py
  course_catalog/migrations/0080_contentfile_image_src.py
  course_catalog/models.py
  search/serializers.py
  search/serializers_test.py
  test_json/test_master.json
Labels: Needs Review
