Repository mitodl/open-discussions, pull requests merged in 2020-03, with the labels that each got.

#2607 Fixed bug with missing popular resources
  interactions/serializers.py
  interactions/serializers_test.py
Labels: Needs Review

#2599 OLX ingestion for xPRO courses
  app.json
  course_catalog/api.py
  course_catalog/api_test.py
  course_catalog/etl/ocw.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/management/commands/backpopulate_xpro_files.py
  course_catalog/models.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  fixtures/aws.py
  open_discussions/settings.py
  requirements.in
  requirements.txt
  search/serializers.py
  search/tasks.py
  search/tasks_test.py
  test_json/empty.tar.gz
  test_json/exported_courses_12345.tar.gz
Labels: Waiting on Author

#2608 Assign a score to child document results
  static/js/lib/search.js
  static/js/lib/search_test.js
Labels: Needs Review

#2619 Allow anonymous users to view the profile page and related posts and comments
  profiles/views.py
  profiles/views_test.py
Labels: Needs Review

#2610 script to generate duplicate courses yaml
  course_catalog/etl/deduplication.py
  course_catalog/etl/deduplication_test.py
  course_catalog/management/commands/print_course_duplicates_yaml.py
Labels: Waiting on Author

#2625 Fix OLL import
  course_catalog/etl/loaders.py
  course_catalog/etl/loaders_test.py
  course_catalog/migrations/0061_image_src_maxlength.py
  course_catalog/models.py
Labels: Waiting on Author

#2620 Fix error reporting when OCWSerializer is invalid
  course_catalog/api.py
  course_catalog/api_test.py
Labels: Waiting on Author

#2628 don't overwrite ocw course with old run data
  course_catalog/api.py
  course_catalog/api_test.py
Labels: Waiting on Author

#2624 Support adding users to MIT-only channels
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  channels/admin.py
  channels/factories/models.py
  channels/management/commands/update_managed_channel_memberships.py
  channels/membership_api.py
  channels/membership_api_test.py
  channels/migrations/0024_channel_membership_config.py
  channels/models.py
  channels/tasks.py
  channels/tasks_test.py
  open_discussions/settings.py
  open_discussions/templates/admin/channels/channelmembershipconfig/change_form.html
  package.json
  profiles/filters.py
  profiles/filters_test.py
  requirements.in
  requirements.txt
  scripts/test/js_test.sh
  yarn.lock
Labels: Waiting on Author

#2680 bump ocw data parser verison
  requirements.in
  requirements.txt
Labels: Waiting on Author

#2627 Moira integration
  app.json
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  channels/__init__.py
  channels/admin.py
  channels/apps.py
  channels/models.py
  channels/models_test.py
  channels/signals.py
  moira_lists/__init__.py
  moira_lists/admin.py
  moira_lists/apps.py
  moira_lists/conftest.py
  moira_lists/exceptions.py
  moira_lists/factories.py
  moira_lists/migrations/0001_initial.py
  moira_lists/migrations/__init__.py
  moira_lists/models.py
  moira_lists/moira_api.py
  moira_lists/moira_api_test.py
  moira_lists/tasks.py
  moira_lists/tasks_test.py
  open_discussions/envs.py
  open_discussions/features.py
  open_discussions/settings.py
  open_discussions/utils.py
  open_discussions/utils_test.py
  profiles/filters.py
  profiles/filters_test.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#2688 raw_json should be write-only on LearningResourceRunSerializer
  course_catalog/serializers.py
  course_catalog/serializers_test.py
Labels: Waiting on Author

#2697 Updated /learn to have per-carousel loaders
  static/js/pages/CourseIndexPage.js
  static/js/pages/CourseIndexPage_test.js
Labels: Needs Review

#2626 Pin redis and nginx versions
  docker-compose.yml
Labels: Waiting on Author

#2698 update ocw-data-parser version to 0.5.0
  requirements.in
  requirements.txt
Labels: Waiting on Author

#2696 Log ProfileDoesNotExist exceptions when updating channel memberships
  channels/membership_api.py
  channels/membership_api_test.py
Labels: Waiting on Author

#2685 refactor course search state to be driven off of URL
  .eslintrc
  static/js/components/CourseFilterDrawer.js
  static/js/components/CourseFilterDrawer_test.js
  static/js/components/CourseSearchbox.js
  static/js/flow/searchTypes.js
  static/js/lib/course_search.js
  static/js/lib/course_search_test.js
  static/js/pages/CourseSearchPage.js
  static/js/pages/CourseSearchPage_test.js
  static/js/pages/admin/EditChannelAppearancePage_test.js
Labels: Waiting on Author

#2631 More intelligent OLX ingestion, and ingest static files for xPRO
  course_catalog/constants.py
  course_catalog/etl/loaders.py
  course_catalog/etl/utils.py
  course_catalog/etl/utils_test.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/migrations/0062_content_type_choices.py
Labels: Waiting on Author

#2684 Use file extension to inform tika about file type for OCW ingestion
  course_catalog/etl/ocw.py
  course_catalog/etl/ocw_test.py
Labels: Waiting on Author

#2687 OCW webhook
  app.json
  course_catalog/exceptions.py
  course_catalog/management/commands/backpopulate_ocw_data.py
  course_catalog/tasks.py
  course_catalog/urls.py
  course_catalog/views.py
  course_catalog/views_test.py
  open_discussions/features.py
  open_discussions/settings.py
  tox.ini
Labels: Waiting on Author

#2707 Update djoser and DRF to fix password reset
  authentication/urls.py
  authentication/views.py
  course_catalog/migrations/0063_intructor_ordering.py
  course_catalog/models.py
  open_discussions/settings.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#2720 remove fuzzy search
  static/js/lib/search.js
  static/js/lib/search_test.js
Labels: Waiting on Author

#2603 Initial proposal for reddit migration work
  docs/reddit-migration/considerations/reddit-ids.md
  docs/reddit-migration/considerations/sorting.md
  docs/reddit-migration/readme.md
  docs/reddit-migration/strategy/cleanup.md
  docs/reddit-migration/strategy/reads-and-writes.md
  docs/reddit-migration/strategy/schema.md
Labels: RFC

#2717 Improved performance of /learn APIs
  course_catalog/etl/loaders_test.py
  course_catalog/migrations/0064_add_indexes.py
  course_catalog/models.py
  course_catalog/serializers.py
  course_catalog/views.py
  interactions/serializers.py
  interactions/serializers_test.py
  interactions/views_test.py
  open_discussions/models.py
Labels: Waiting on Author
