Repository mitodl/open-discussions, pull requests merged in 2022-08, with the labels that each got.

#3661 Field edit page with preliminary appearance tab
  channels_fields/admin.py
  channels_fields/api.py
  channels_fields/migrations/0006_description_textfield.py
  channels_fields/models.py
  channels_fields/permissions.py
  channels_fields/serializers.py
  channels_fields/serializers_test.py
  channels_fields/views_test.py
  discussions/models.py
  frontends/infinite-corridor/package.json
  frontends/infinite-corridor/src/App.tsx
  frontends/infinite-corridor/src/api/fields/factories.ts
  frontends/infinite-corridor/src/api/fields/hooks.ts
  frontends/infinite-corridor/src/api/fields/index.ts
  frontends/infinite-corridor/src/api/fields/interfaces.ts
  frontends/infinite-corridor/src/api/fields/urls.ts
  frontends/infinite-corridor/src/components/FieldAvatar.test.tsx
  frontends/infinite-corridor/src/components/FieldAvatar.tsx
  frontends/infinite-corridor/src/libs/axios.ts
  frontends/infinite-corridor/src/pages/FieldPageSkeleton.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldAppearanceForm.test.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldAppearanceForm.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldPage.test.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldPage.tsx
  frontends/infinite-corridor/src/pages/admin/FieldAdminApp.tsx
  frontends/infinite-corridor/src/pages/urls.ts
  frontends/infinite-corridor/src/scss/admin.scss
  frontends/infinite-corridor/src/scss/combined.scss
  frontends/infinite-corridor/src/scss/fieldpage.scss
  frontends/infinite-corridor/src/scss/form.scss
  frontends/infinite-corridor/src/scss/theme.scss
  frontends/infinite-corridor/src/test-utils/index.tsx
  frontends/infinite-corridor/tsconfig.json
  frontends/ol-forms/package.json
  frontends/ol-util/package.json
  frontends/ol-util/src/index.ts
  frontends/ol-util/src/lib/index.ts
  frontends/ol-util/src/lib/utils.ts
  open_discussions/settings.py
  yarn.lock
Labels: Waiting on Author

#3670 fix useSearchParams
  frontends/ol-util/src/hooks/useSearchParams.test.tsx
  frontends/ol-util/src/hooks/useSearchParams.ts
Labels: Needs Review

#3669 rtl tests for search
  frontends/infinite-corridor/jest.config.ts
  frontends/infinite-corridor/src/pages/HomePage.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.tsx
  frontends/infinite-corridor/src/test-utils/setupJest.ts
  frontends/infinite-corridor/src/test-utils/testing_init.ts
Labels: Waiting on Author

#3665 Cc/field pages v1
  frontends/infinite-corridor/src/api/fields/factories.ts
  frontends/infinite-corridor/src/api/fields/hooks.ts
  frontends/infinite-corridor/src/api/fields/interfaces.ts
  frontends/infinite-corridor/src/api/fields/urls.ts
  frontends/infinite-corridor/src/components/FieldAvatar.test.tsx
  frontends/infinite-corridor/src/components/FieldAvatar.tsx
  frontends/infinite-corridor/src/components/Header.test.tsx
  frontends/infinite-corridor/src/pages/FieldPage.test.tsx
  frontends/infinite-corridor/src/pages/FieldPage.tsx
  frontends/infinite-corridor/src/pages/HomePage.test.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldAppearanceForm.test.tsx
  frontends/infinite-corridor/src/scss/fieldpage.scss
  frontends/infinite-corridor/src/scss/learning-resources.scss
  frontends/infinite-corridor/src/scss/theme.scss
  frontends/infinite-corridor/src/test-utils/setupJest.ts
  frontends/infinite-corridor/src/util/constants.ts
  frontends/ol-search-ui/assets/learning-resource-card.scss
  frontends/ol-search-ui/src/components/LearningResourceCard.tsx
  frontends/ol-search-ui/src/components/index.ts
  frontends/ol-search-ui/src/factories.ts
  frontends/ol-search-ui/src/interfaces.ts
  frontends/ol-util/package.json
  frontends/ol-util/src/components/TitledCarousel.test.tsx
  frontends/ol-util/src/components/TitledCarousel.tsx
  frontends/ol-util/src/components/index.ts
  frontends/ol-util/src/factories.ts
  yarn.lock
Labels: Waiting on Author

#3673 Fix styling conflicts: remove some classless tag selectors
  frontends/infinite-corridor/src/pages/admin/EditFieldAppearanceForm.tsx
  frontends/infinite-corridor/src/scss/combined.scss
  frontends/infinite-corridor/src/scss/form.scss
Labels: Waiting on Author

#3674 Set imagekit prefix to ""
  app.json
  open_discussions/settings.py
Labels: Waiting on Author

#3676 Fix open discussions channel header issue
  frontends/ol-util/src/components/PageBanner.tsx
Labels: Waiting on Author

#3679 Cc/styling tweaks
  frontends/infinite-corridor/src/components/Header.test.tsx
  frontends/infinite-corridor/src/components/Header.tsx
  frontends/infinite-corridor/src/pages/FieldPage.test.tsx
  frontends/infinite-corridor/src/pages/FieldPage.tsx
  frontends/infinite-corridor/src/pages/FieldPageSkeleton.tsx
  frontends/infinite-corridor/src/pages/HomePage.test.tsx
  frontends/infinite-corridor/src/pages/HomePage.tsx
  frontends/infinite-corridor/src/pages/SearchPage.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldPage.tsx
  frontends/infinite-corridor/src/scss/combined.scss
  frontends/infinite-corridor/src/scss/fieldpage.scss
  frontends/infinite-corridor/src/scss/form.scss
  frontends/infinite-corridor/src/scss/header.scss
  frontends/infinite-corridor/src/scss/homepage.scss
  frontends/infinite-corridor/src/scss/learning-resources.scss
  frontends/infinite-corridor/src/scss/main-search.scss
  frontends/infinite-corridor/src/scss/mui.scss
  frontends/infinite-corridor/src/scss/searchpage.scss
  frontends/infinite-corridor/src/scss/theme.scss
  frontends/ol-search-ui/src/components/LearningResourceCard.tsx
Labels: Waiting on Author

#3683 facets
  frontends/infinite-corridor/src/components/SearchFilter.tsx
  frontends/infinite-corridor/src/pages/SearchPage.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.tsx
  frontends/infinite-corridor/src/scss/main-search.scss
  frontends/infinite-corridor/src/scss/searchpage.scss
  frontends/infinite-corridor/src/scss/theme.scss
  frontends/ol-search-ui/src/components/Facet.tsx
  frontends/ol-search-ui/src/components/FacetDisplay.test.tsx
  frontends/ol-search-ui/src/components/FacetDisplay.tsx
  frontends/ol-search-ui/src/components/SearchFacetItem.tsx
  frontends/ol-search-ui/src/components/SearchFilter.test.tsx
  frontends/ol-search-ui/src/components/SearchFilter.tsx
  frontends/ol-search-ui/src/components/SearchFilterDrawer.tsx
  frontends/ol-search-ui/src/components/index.ts
  frontends/ol-search-ui/src/factories.ts
  frontends/ol-search-ui/src/interfaces.ts
  frontends/ol-search-ui/src/util.ts
Labels: Waiting on Author

#3685 search styles
  frontends/infinite-corridor/src/pages/HomePage.tsx
  frontends/infinite-corridor/src/pages/SearchPage.tsx
  frontends/infinite-corridor/src/scss/_breakpoints.scss
  frontends/infinite-corridor/src/scss/header.scss
  frontends/infinite-corridor/src/scss/learning-resources.scss
  frontends/infinite-corridor/src/scss/main-search.scss
  frontends/infinite-corridor/src/scss/searchpage.scss
  frontends/ol-search-ui/src/components/Facet.tsx
  frontends/ol-search-ui/src/components/FacetDisplay.test.tsx
  frontends/ol-search-ui/src/components/FacetDisplay.tsx
  frontends/ol-search-ui/src/components/LearningResourceCard.tsx
  frontends/ol-search-ui/src/components/SearchFacetItem.tsx
  frontends/ol-search-ui/src/components/SearchFilterDrawer.tsx
  frontends/ol-search-ui/src/factories.ts
  frontends/ol-search-ui/src/util.tsx
  frontends/ol-util/src/lib/index.ts
  frontends/ol-util/src/lib/utils.ts
  static/images/certificate_icon_infinite.png
Labels: Waiting on Author

#3682 Basic field edit form (add/remove/sort lists)
  frontends/infinite-corridor/src/api/fields/factories.ts
  frontends/infinite-corridor/src/api/fields/hooks.ts
  frontends/infinite-corridor/src/api/fields/interfaces.ts
  frontends/infinite-corridor/src/api/fields/urls.ts
  frontends/infinite-corridor/src/pages/admin/EditFieldAppearanceForm.test.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldAppearanceForm.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldBasicForm.test.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldBasicForm.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldPage.test.tsx
  frontends/infinite-corridor/src/pages/admin/EditFieldPage.tsx
  frontends/infinite-corridor/src/scss/form.scss
  frontends/ol-forms/package.json
  frontends/ol-forms/src/components/SelectField.test.tsx
  frontends/ol-forms/src/components/SelectField.tsx
  frontends/ol-forms/src/components/SortWrapper.tsx
  frontends/ol-forms/src/components/SortableItem.test.tsx
  frontends/ol-forms/src/components/SortableItem.tsx
  frontends/ol-forms/src/components/SortableSelect.test.tsx
  frontends/ol-forms/src/components/SortableSelect.tsx
  frontends/ol-forms/src/components/index.ts
  yarn.lock
Labels: Needs Review

#3689 Move widget/group creation for fields to signal
  channels_fields/__init__.py
  channels_fields/admin.py
  channels_fields/api.py
  channels_fields/apps.py
  channels_fields/migrations/0007_blankable_images.py
  channels_fields/serializers.py
  channels_fields/serializers_test.py
  channels_fields/signals.py
  discussions/migrations/0003_blankable_images.py
  discussions/models.py
Labels: Waiting on Author

#3693 FieldChannel banner menu dropdown
  frontends/infinite-corridor/src/components/FieldMenu.test.tsx
  frontends/infinite-corridor/src/components/FieldMenu.tsx
  frontends/infinite-corridor/src/pages/FieldPageSkeleton.tsx
  frontends/infinite-corridor/src/pages/urls.ts
  frontends/infinite-corridor/src/scss/fieldpage.scss
Labels: Waiting on Author

#3692 Cc/styling 2
  frontends/infinite-corridor/src/pages/FieldPage.test.tsx
  frontends/infinite-corridor/src/pages/FieldPage.tsx
  frontends/infinite-corridor/src/scss/buttons.scss
  frontends/infinite-corridor/src/scss/combined.scss
  frontends/infinite-corridor/src/scss/fieldpage.scss
  frontends/infinite-corridor/src/scss/learning-resources.scss
  frontends/ol-search-ui/assets/learning-resource-card.scss
  frontends/ol-search-ui/src/components/LearningResourceCard.tsx
  frontends/ol-util/src/components/TitledCarousel.tsx
Labels: Needs Review

#3699 Viewing (plaintext) widgets
  frontends/infinite-corridor/package.json
  frontends/infinite-corridor/src/App.tsx
  frontends/infinite-corridor/src/api/fields/factories.ts
  frontends/infinite-corridor/src/api/fields/interfaces.ts
  frontends/infinite-corridor/src/api/widgets/hooks.ts
  frontends/infinite-corridor/src/api/widgets/index.ts
  frontends/infinite-corridor/src/api/widgets/urls.ts
  frontends/infinite-corridor/src/pages/HomePage.test.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldAppearanceForm.test.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldAppearanceForm.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldBasicForm.test.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldBasicForm.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldPage.test.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldPage.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldAdminApp.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.test.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPageSkeleton.tsx
  frontends/infinite-corridor/src/pages/field-details/WidgetsList.spec.tsx
  frontends/infinite-corridor/src/pages/field-details/WidgetsList.tsx
  frontends/infinite-corridor/src/pages/field-details/components/FieldAvatar.test.tsx
  frontends/infinite-corridor/src/pages/field-details/components/FieldAvatar.tsx
  frontends/infinite-corridor/src/pages/field-details/components/FieldMenu.test.tsx
  frontends/infinite-corridor/src/pages/field-details/components/FieldMenu.tsx
  frontends/infinite-corridor/src/pages/urls.ts
  frontends/infinite-corridor/src/scss/fieldpage.scss
  frontends/infinite-corridor/src/scss/learning-resources.scss
  frontends/infinite-corridor/src/scss/mui.scss
  frontends/infinite-corridor/src/test-utils/index.tsx
  frontends/ol-util/src/factories.ts
  frontends/ol-widgets/jest.config.ts
  frontends/ol-widgets/package.json
  frontends/ol-widgets/src/components/RichTextWidget.tsx
  frontends/ol-widgets/src/components/Widget-RichText.spec.tsx
  frontends/ol-widgets/src/components/Widget.tsx
  frontends/ol-widgets/src/components/index.ts
  frontends/ol-widgets/src/factories.ts
  frontends/ol-widgets/src/index.ts
  frontends/ol-widgets/src/interfaces.ts
  frontends/ol-widgets/tsconfig.json
  yarn.lock
Labels: Waiting on Author

#3705 Handle non-numerical status codes from elasticsearch
  search/views.py
  search/views_test.py
Labels: Waiting on Author

#3704 Heroku-22 compatibility
  Aptfile
  apt.txt
  requirements.in
  requirements.txt
Labels: Needs Review

#3702 Widget Editing in Infinite Corridor
  frontends/infinite-corridor/package.json
  frontends/infinite-corridor/src/api/widgets/hooks.ts
  frontends/infinite-corridor/src/libs/mui.ts
  frontends/infinite-corridor/src/pages/field-details/EditFieldPage.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.test.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.tsx
  frontends/infinite-corridor/src/pages/field-details/WidgetsList.spec.tsx
  frontends/infinite-corridor/src/pages/field-details/WidgetsList.tsx
  frontends/infinite-corridor/src/pages/field-details/components/FieldMenu.test.tsx
  frontends/infinite-corridor/src/pages/field-details/components/FieldMenu.tsx
  frontends/infinite-corridor/src/pages/urls.ts
  frontends/infinite-corridor/src/scss/buttons.scss
  frontends/infinite-corridor/src/scss/combined.scss
  frontends/infinite-corridor/src/scss/fieldpage.scss
  frontends/infinite-corridor/src/scss/mui.scss
  frontends/infinite-corridor/src/scss/theme.scss
  frontends/infinite-corridor/src/scss/widgets.scss
  frontends/ol-forms/src/components/SortableItem.test.tsx
  frontends/ol-forms/src/components/SortableItem.tsx
  frontends/ol-search-ui/src/factories.ts
  frontends/ol-util/src/hooks/index.ts
  frontends/ol-util/src/hooks/useId.ts
  frontends/ol-widgets/assets/widgets.scss
  frontends/ol-widgets/package.json
  frontends/ol-widgets/src/components/RichTextWidget.tsx
  frontends/ol-widgets/src/components/RichTextWidgetContent.tsx
  frontends/ol-widgets/src/components/Widget.spec.tsx
  frontends/ol-widgets/src/components/Widget.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog.spec.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog.tsx
  frontends/ol-widgets/src/components/editing/WidgetsListEditable.spec.tsx
  frontends/ol-widgets/src/components/editing/WidgetsListEditable.tsx
  frontends/ol-widgets/src/components/editing/getWidgetFieldComponent.tsx
  frontends/ol-widgets/src/components/editing/index.tsx
  frontends/ol-widgets/src/components/editing/schemas.tsx
  frontends/ol-widgets/src/components/index.ts
  frontends/ol-widgets/src/constants.ts
  frontends/ol-widgets/src/factories.ts
  frontends/ol-widgets/src/interfaces.ts
  yarn.lock
Labels: Needs Review, Blocker

#3700 Import and index MITX Online courses and content
  app.json
  course_catalog/api.py
  course_catalog/api_test.py
  course_catalog/constants.py
  course_catalog/etl/mitx.py
  course_catalog/etl/mitxonline.py
  course_catalog/etl/mitxonline_test.py
  course_catalog/etl/pipelines.py
  course_catalog/etl/utils.py
  course_catalog/etl/utils_test.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/management/commands/backpopulate_mitxonline_data.py
  course_catalog/management/commands/backpopulate_mitxonline_files.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  fixtures/aws.py
  fixtures/common.py
  frontends/open-discussions/src/lib/constants.js
  open_discussions/settings.py
  static/images/mitx-online-logo.png
  test_json/course-v1:MITxT+8.01.3x+3T2022.tar.gz
  test_json/course-v1:MITxT+8.01.4x+3T2022.tar.gz
  test_json/mitxonline_courses.json
  test_json/mitxonline_programs.json
Labels: Needs Review, Waiting on Author
