Repository mitodl/open-discussions, pull requests merged in 2022-09, with the labels that each got.

#3713 support richtext editing/display in ol-widgets
  frontends/infinite-corridor/jest.config.ts
  frontends/infinite-corridor/package.json
  frontends/infinite-corridor/src/pages/field-details/WidgetsList.test.tsx
  frontends/infinite-corridor/src/scss/buttons.scss
  frontends/infinite-corridor/src/scss/widgets.scss
  frontends/infinite-corridor/src/test-utils/setupJest.ts
  frontends/infinite-corridor/webpack.config.js
  frontends/ol-widgets/assets/widgets.scss
  frontends/ol-widgets/jest.config.ts
  frontends/ol-widgets/package.json
  frontends/ol-widgets/src/components/RichTextWidgetContent.tsx
  frontends/ol-widgets/src/components/Widget-RichText.spec.tsx
  frontends/ol-widgets/src/components/Widget-RichText.test.tsx
  frontends/ol-widgets/src/components/Widget.test.tsx
  frontends/ol-widgets/src/components/Widget.tsx
  frontends/ol-widgets/src/components/editing/CkeditorMarkdown.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog.test.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog.tsx
  frontends/ol-widgets/src/components/editing/MarkdownEditor.tsx
  frontends/ol-widgets/src/components/editing/WidgetsListEditable.test.tsx
  frontends/ol-widgets/src/components/editing/getWidgetFieldComponent.tsx
  frontends/ol-widgets/src/components/editing/interfaces.ts
  frontends/ol-widgets/src/factories.ts
  frontends/ol-widgets/src/setupJest.ts
  frontends/ol-widgets/src/test-utils/index.tsx
  frontends/ol-widgets/src/types/ckeditor.d.ts
  yarn.lock
Labels: Needs Review

#3708 infinite drawer
  frontends/infinite-corridor/src/pages/SearchPage.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.tsx
  frontends/infinite-corridor/src/scss/learning-resources.scss
  frontends/infinite-corridor/src/test-utils/index.tsx
  frontends/ol-search-ui/assets/learning-resource-card.scss
  frontends/ol-search-ui/assets/learning-resource-drawer.scss
  frontends/ol-search-ui/jest.config.ts
  frontends/ol-search-ui/src/components/ExpandedLearningResourceDisplay.test.tsx
  frontends/ol-search-ui/src/components/ExpandedLearningResourceDisplay.tsx
  frontends/ol-search-ui/src/components/LearningResourceCard.test.tsx
  frontends/ol-search-ui/src/components/LearningResourceCard.tsx
  frontends/ol-search-ui/src/components/LearningResourceDrawer.test.tsx
  frontends/ol-search-ui/src/components/LearningResourceDrawer.tsx
  frontends/ol-search-ui/src/components/ShareTooltip.tsx
  frontends/ol-search-ui/src/components/TruncatedText.tsx
  frontends/ol-search-ui/src/components/index.ts
  frontends/ol-search-ui/src/factories.ts
  frontends/ol-search-ui/src/interfaces.ts
  frontends/ol-search-ui/src/types/settings.d.ts
  frontends/ol-search-ui/src/util.tsx
  package.json
  yarn.lock
Labels: Waiting on Author

#3717 Enforce uniqueness for instructor full name, get rid of existing dupes
  course_catalog/migrations/0091_instructor_runs.py
  course_catalog/migrations/0092_remove_instructor_dupes.py
  course_catalog/migrations/0093_instructor_fullname_unique.py
  course_catalog/models.py
Labels: Needs Review

#3723 Use jest-watch-typeahead to get live file matches in jest runner
  jest.config.ts
  package.json
  yarn.lock
Labels: Needs Review

#3721 Cc/url widget
  frontends/infinite-corridor/src/pages/field-details/WidgetsList.tsx
  frontends/infinite-corridor/src/scss/form.scss
  frontends/ol-widgets/assets/widgets.scss
  frontends/ol-widgets/package.json
  frontends/ol-widgets/src/components/EmbeddedUrlWidgetContent.tsx
  frontends/ol-widgets/src/components/Widget-EmbeddedUrl.test.tsx
  frontends/ol-widgets/src/components/Widget-RichText.test.tsx
  frontends/ol-widgets/src/components/Widget.test.tsx
  frontends/ol-widgets/src/components/Widget.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog-EmbeddedUrl.test.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog.test.tsx
  frontends/ol-widgets/src/components/editing/ManageWidgetDialog.tsx
  frontends/ol-widgets/src/components/editing/UrlField.tsx
  frontends/ol-widgets/src/components/editing/WidgetsListEditable.tsx
  frontends/ol-widgets/src/components/editing/getWidgetFieldComponent.tsx
  frontends/ol-widgets/src/components/editing/index.tsx
  frontends/ol-widgets/src/components/editing/interfaces.ts
  frontends/ol-widgets/src/components/editing/schemas.tsx
  frontends/ol-widgets/src/components/editing/widgetFields.tsx
  frontends/ol-widgets/src/components/embedly/EmbedlyCard.test.tsx
  frontends/ol-widgets/src/components/embedly/EmbedlyCard.tsx
  frontends/ol-widgets/src/components/embedly/index.ts
  frontends/ol-widgets/src/components/embedly/util.test.ts
  frontends/ol-widgets/src/components/embedly/util.ts
  frontends/ol-widgets/src/constants.ts
  frontends/ol-widgets/src/factories.ts
  frontends/ol-widgets/src/interfaces.ts
  frontends/ol-widgets/src/setupJest.ts
  frontends/ol-widgets/src/types/settings.d.ts
  yarn.lock
Labels: Needs Review

#3725 Cc/smaller bundle
  .env.example
  frontends/infinite-corridor/package.json
  frontends/infinite-corridor/src/api/fields/factories.ts
  frontends/infinite-corridor/src/pages/HomePage.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldAppearanceForm.test.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldBasicForm.test.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.test.tsx
  frontends/infinite-corridor/src/pages/field-details/WidgetsList.test.tsx
  frontends/infinite-corridor/src/scss/admin.scss
  frontends/infinite-corridor/src/scss/fieldpage.scss
  frontends/infinite-corridor/webpack.config.js
  frontends/ol-forms/package.json
  frontends/ol-forms/src/components/SelectField.tsx
  frontends/ol-search-ui/assets/learning-resource-card.scss
  frontends/ol-search-ui/package.json
  frontends/ol-search-ui/src/components/ExpandedLearningResourceDisplay.tsx
  frontends/ol-search-ui/src/components/Facet.tsx
  frontends/ol-search-ui/src/factories.ts
  frontends/ol-search-ui/src/index.ts
  frontends/ol-search-ui/src/util.tsx
  frontends/ol-util/package.json
  frontends/ol-util/src/factories.ts
  frontends/ol-util/src/index.ts
  frontends/ol-util/src/lib/index.ts
  frontends/ol-util/src/lib/utils.test.ts
  frontends/ol-util/src/lib/utils.ts
  frontends/ol-widgets/src/factories.ts
  frontends/ol-widgets/src/index.ts
  frontends/open-discussions/package.json
  frontends/open-discussions/webpack.config.js
  package.json
  yarn.lock
Labels: Needs Review

#3736 Remove transient errors in start-dev
  package.json
  scripts/run-watch-dev.sh
Labels: Waiting on Author

#3735 Set published=False for openedx courses if no runs are published
  course_catalog/etl/mitx_test.py
  course_catalog/etl/openedx.py
  course_catalog/etl/openedx_test.py
  test_json/test_mitx_course.json
Labels: Needs Review, Waiting on Author

#3743 Refactor xpro course file sync
  course_catalog/etl/edx_shared.py
  course_catalog/etl/edx_shared_test.py
  course_catalog/etl/mitxonline.py
  course_catalog/etl/mitxonline_test.py
  course_catalog/etl/utils_test.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
Labels: Waiting on Author

#3742 Wider widget sidebar; more consistent breakpoints
  frontends/infinite-corridor/src/components/layout.tsx
  frontends/infinite-corridor/src/libs/mui.ts
  frontends/infinite-corridor/src/pages/SearchPage.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldPage.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.tsx
  frontends/infinite-corridor/src/scss/_breakpoints.scss
  frontends/infinite-corridor/src/scss/breakpoints.scss
  frontends/infinite-corridor/src/scss/header.scss
  frontends/infinite-corridor/src/scss/learning-resources.scss
  frontends/infinite-corridor/src/scss/main-search.scss
  frontends/infinite-corridor/src/scss/searchpage.scss
  frontends/infinite-corridor/src/scss/theme.scss
  frontends/infinite-corridor/src/test-utils/setupJest.ts
  frontends/ol-search-ui/src/components/SearchFilterDrawer.tsx
  frontends/ol-util/src/lib/index.ts
  frontends/ol-util/src/lib/utils.ts
  frontends/ol-util/src/test-utils/index.test.ts
  frontends/ol-util/src/test-utils/index.ts
  package.json
  yarn.lock
Labels: Waiting on Author

#3749 Remove bootcamps, csail, mitpe, see platform courses
  course_catalog/api.py
  course_catalog/api_test.py
  course_catalog/constants.py
  course_catalog/etl/csail.py
  course_catalog/etl/csail_test.py
  course_catalog/etl/mitpe.py
  course_catalog/etl/mitpe_test.py
  course_catalog/etl/pipelines.py
  course_catalog/etl/pipelines_test.py
  course_catalog/etl/see.py
  course_catalog/etl/see_test.py
  course_catalog/factories.py
  course_catalog/management/commands/backpopulate_bootcamp_data.py
  course_catalog/management/commands/backpopulate_csail_data.py
  course_catalog/management/commands/backpopulate_mitpe_data.py
  course_catalog/management/commands/backpopulate_see_data.py
  course_catalog/management/commands/delete_courses.py
  course_catalog/models.py
  course_catalog/models_test.py
  course_catalog/serializers_test.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  open_discussions/settings.py
  search/tasks_test.py
Labels: Waiting on Author

#3732 Update course-search-utils to fix routing issue
  frontends/infinite-corridor/package.json
  frontends/infinite-corridor/src/pages/SearchPage.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.tsx
  frontends/ol-search-ui/package.json
  frontends/ol-util/package.json
  frontends/open-discussions/package.json
  frontends/open-discussions/src/pages/CourseSearchPage.js
  frontends/open-discussions/src/pages/CourseSearchPage_test.js
  package.json
  yarn.lock
Labels: Waiting on Author

#3753 Connect LearningResource Drawer to router
  .eslintrc.js
  frontends/infinite-corridor/src/App.tsx
  frontends/infinite-corridor/src/api/fields/factories.ts
  frontends/infinite-corridor/src/api/learning-resources/hooks.ts
  frontends/infinite-corridor/src/api/learning-resources/index.ts
  frontends/infinite-corridor/src/api/learning-resources/urls.ts
  frontends/infinite-corridor/src/components/RoutedDrawer.test.tsx
  frontends/infinite-corridor/src/components/RoutedDrawer.tsx
  frontends/infinite-corridor/src/pages/LearningResourceDrawer.tsx
  frontends/infinite-corridor/src/pages/SearchPage.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.test.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.tsx
  frontends/infinite-corridor/src/scss/learning-resources.scss
  frontends/infinite-corridor/src/test-utils/setupJest.ts
  frontends/infinite-corridor/src/util/constants.ts
  frontends/ol-search-ui/assets/learning-resource-drawer.scss
  frontends/ol-search-ui/src/components/ExpandedLearningResourceDisplay.test.tsx
  frontends/ol-search-ui/src/components/ExpandedLearningResourceDisplay.tsx
  frontends/ol-search-ui/src/components/LearningResourceCard.tsx
  frontends/ol-search-ui/src/components/LearningResourceDrawer.test.tsx
  frontends/ol-search-ui/src/components/LearningResourceDrawer.tsx
  frontends/ol-search-ui/src/components/index.ts
  frontends/ol-search-ui/src/factories.ts
  frontends/ol-search-ui/src/interfaces.ts
  frontends/ol-search-ui/src/util.tsx
  frontends/ol-util/src/factories.ts
  frontends/ol-util/src/predicates.ts
  frontends/ol-util/src/test-utils/index.ts
  package.json
  yarn.lock
Labels: Needs Review
