Repository mitodl/open-discussions, pull requests merged in 2023-05, with the labels that each got.

#3973 UI for Staff Lists Listing page
  frontends/infinite-corridor/src/App.tsx
  frontends/infinite-corridor/src/api/learning-resources/hooks.test.tsx
  frontends/infinite-corridor/src/api/learning-resources/hooks.ts
  frontends/infinite-corridor/src/api/learning-resources/urls.ts
  frontends/infinite-corridor/src/components/BasicDialog.tsx
  frontends/infinite-corridor/src/components/LearningResourceCard.spec.tsx
  frontends/infinite-corridor/src/components/LearningResourceCard.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldBasicForm.test.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/AddToListDialog.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/AddToListDialog.tsx
  frontends/infinite-corridor/src/pages/resource-lists/EditListMenu.tsx
  frontends/infinite-corridor/src/pages/resource-lists/FavoritesPage.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/FavoritesPage.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ItemsListing.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ItemsListing.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ManageListDialogs.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ManageListDialogs.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ResourceListsListingsPage.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ResourceListsListingsPage.tsx
  frontends/infinite-corridor/src/pages/resource-lists/UserListDetailsPage.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/UserListDetailsPage.tsx
  frontends/infinite-corridor/src/pages/urls.ts
  frontends/infinite-corridor/src/pages/user-lists/ManageListDialogs.test.tsx
  frontends/infinite-corridor/src/pages/user-lists/ManageListDialogs.tsx
  frontends/infinite-corridor/src/pages/user-lists/UpsertListDialog.tsx
  frontends/infinite-corridor/src/pages/user-lists/UserListsListingPage.test.tsx
  frontends/ol-forms/src/components/FormDialog.tsx
  frontends/ol-forms/src/components/RadioChoiceField.tsx
  frontends/ol-forms/src/components/index.ts
  frontends/ol-search-ui/src/components/LearningResourceCardTemplate.test.tsx
  frontends/ol-search-ui/src/components/LearningResourceCardTemplate.tsx
  frontends/ol-search-ui/src/factories.ts
  frontends/ol-search-ui/src/interfaces.ts
  frontends/ol-search-ui/src/util.tsx
Labels: Waiting on Author

#3976 Handle unicode chars when truncating file content
  search/serializers.py
  search/serializers_test.py
Labels: Needs Review

#3982 improve setMockResponse manual response resolution
  frontends/infinite-corridor/src/example-request-mocks.test.ts
  frontends/infinite-corridor/src/test-utils/mockAxios.ts
Labels: Waiting on Author

#3983 Details page + AddToListDialog for stafflists
  frontends/infinite-corridor/src/App.tsx
  frontends/infinite-corridor/src/api/learning-resources/hooks.test.tsx
  frontends/infinite-corridor/src/api/learning-resources/hooks.ts
  frontends/infinite-corridor/src/api/learning-resources/urls.ts
  frontends/infinite-corridor/src/api/learning-resources/util.test.tsx
  frontends/infinite-corridor/src/api/learning-resources/util.ts
  frontends/infinite-corridor/src/components/LearningResourceCard.spec.tsx
  frontends/infinite-corridor/src/components/LearningResourceCard.tsx
  frontends/infinite-corridor/src/pages/resource-lists/AddToListDialog.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/AddToListDialog.tsx
  frontends/infinite-corridor/src/pages/resource-lists/FavoritesPage.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ItemsListing.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ItemsListing.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ManageListDialogs.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ResourceListDetailsPage.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ResourceListDetailsPage.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ResourceListsListingsPage.tsx
  frontends/infinite-corridor/src/pages/resource-lists/UserListDetailsPage.test.tsx
  frontends/infinite-corridor/src/test-utils/factories.ts
  frontends/infinite-corridor/src/test-utils/index.tsx
  frontends/infinite-corridor/src/types/settings.d.ts
  frontends/ol-search-ui/src/factories.ts
  frontends/ol-search-ui/src/index.ts
  frontends/ol-search-ui/src/interfaces.ts
  frontends/ol-search-ui/src/util.test.ts
  frontends/ol-search-ui/src/util.tsx
  frontends/open-discussions/src/components/UserListItems.js
  infinite_example/views.py
Labels: Waiting on Author

#3974 Elasticsearch 7.10 upgrade
  .github/workflows/ci.yml
  course_catalog/etl/loaders_test.py
  docker-compose.yml
  fixtures/elasticsearch.py
  requirements.in
  requirements.txt
  search/api.py
  search/api_test.py
  search/indexing_api.py
Labels: Waiting on Author

#3987 fix resource type facet
  frontends/infinite-corridor/package.json
  frontends/infinite-corridor/src/api/learning-resources/search.ts
  frontends/ol-search-ui/package.json
  frontends/open-discussions/package.json
  frontends/open-discussions/src/lib/api/api.js
  frontends/open-discussions/src/lib/api/api_test.js
  frontends/open-discussions/src/pages/CourseSearchPage.js
  frontends/open-discussions/src/pages/CourseSearchPage_test.js
  frontends/open-discussions/src/pages/SearchPage.js
  frontends/open-discussions/src/pages/SearchPage_test.js
  yarn.lock
Labels: Waiting on Author, do not merge

#3992 Revert "Elasticsearch 7.10 upgrade"
  .github/workflows/ci.yml
  course_catalog/etl/loaders_test.py
  docker-compose.yml
  fixtures/elasticsearch.py
  requirements.in
  requirements.txt
  search/api.py
  search/api_test.py
  search/indexing_api.py
Labels: Waiting on Author

#3991 Ab/dont search all indexes for all queries
  search/api.py
  search/api_test.py
Labels: Waiting on Author

#3989 Update react query
  frontends/infinite-corridor/package.json
  frontends/infinite-corridor/src/App.tsx
  frontends/infinite-corridor/src/api/fields/hooks.ts
  frontends/infinite-corridor/src/api/learning-resources/hooks.test.tsx
  frontends/infinite-corridor/src/api/learning-resources/hooks.ts
  frontends/infinite-corridor/src/api/learning-resources/search.test.tsx
  frontends/infinite-corridor/src/api/learning-resources/search.ts
  frontends/infinite-corridor/src/api/learning-resources/util.test.tsx
  frontends/infinite-corridor/src/api/learning-resources/util.ts
  frontends/infinite-corridor/src/api/widgets/hooks.ts
  frontends/infinite-corridor/src/components/Header.test.tsx
  frontends/infinite-corridor/src/example-request-mocks.test.ts
  frontends/infinite-corridor/src/libs/react-query.test.tsx
  frontends/infinite-corridor/src/libs/react-query.ts
  frontends/infinite-corridor/src/pages/HomePage.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldBasicForm.test.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ItemsListing.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ItemsListing.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ManageListDialogs.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ResourceListDetailsPage.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ResourceListDetailsPage.tsx
  frontends/ol-forms/src/components/FormDialog.test.tsx
  frontends/ol-search-ui/src/util.tsx
  frontends/ol-util/src/test-utils/ControlledPromise.test.ts
  frontends/ol-util/src/test-utils/ControlledPromise.ts
  frontends/ol-util/src/test-utils/index.ts
  jest-shared-setup.ts
  yarn.lock
Labels: Needs Review

#3993 Elasticsearch 7.10 client only (PR 1 of 3)
  .github/workflows/ci.yml
  .secrets.baseline
  course_catalog/etl/loaders_test.py
  fixtures/elasticsearch.py
  requirements.in
  requirements.txt
  search/api_test.py
  search/indexing_api.py
Labels: Needs Review

#3998 Ab/fix aggregations
  frontends/infinite-corridor/package.json
  frontends/infinite-corridor/src/api/learning-resources/search.ts
  frontends/infinite-corridor/src/pages/SearchPage.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.tsx
  frontends/ol-search-ui/package.json
  frontends/open-discussions/package.json
  frontends/open-discussions/src/lib/api/api.js
  frontends/open-discussions/src/pages/CourseSearchPage.js
  frontends/open-discussions/src/pages/CourseSearchPage_test.js
  yarn.lock
Labels: Waiting on Author, do not merge

#3984 Delete orphaned indices after a failed reindex
  search/indexing_api.py
  search/indexing_api_test.py
  search/tasks.py
  search/tasks_test.py
Labels: Waiting on Author

#4007 Use React 18 in New Pages
  frontends/infinite-corridor/package.json
  frontends/infinite-corridor/postcss.config.js
  frontends/infinite-corridor/src/App.tsx
  frontends/infinite-corridor/src/api/learning-resources/favorites.test.tsx
  frontends/infinite-corridor/src/api/learning-resources/resourceLists.test.tsx
  frontends/infinite-corridor/src/api/learning-resources/search.test.tsx
  frontends/infinite-corridor/src/api/learning-resources/util.test.tsx
  frontends/infinite-corridor/src/entry/root.tsx
  frontends/infinite-corridor/src/libs/react-query.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.test.tsx
  frontends/infinite-corridor/src/pages/field-details/WidgetsList.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/FavoritesPage.test.tsx
  frontends/infinite-corridor/src/pages/resource-lists/ResourceListDetailsPage.test.tsx
  frontends/infinite-corridor/src/test-utils/index.tsx
  frontends/ol-search-ui/package.json
  frontends/ol-util/src/hooks/useToggle.test.ts
  frontends/open-discussions/.eslintrc
  frontends/open-discussions/.eslintrc.js
  frontends/open-discussions/.sass-lint.yml
  frontends/open-discussions/package.json
  frontends/open-discussions/postcss.config.js
  package.json
  postcss.config.js
  yarn.lock
Labels: Waiting on Author
