Repository mitodl/open-discussions, pull requests merged in 2023-03, with the labels that each got.

#3849 Add stylelint for scss linting
  .stylelintrc.yaml
  frontends/infinite-corridor/src/scss/admin.scss
  frontends/infinite-corridor/src/scss/breakpoints.scss
  frontends/infinite-corridor/src/scss/buttons.scss
  frontends/infinite-corridor/src/scss/combined.scss
  frontends/infinite-corridor/src/scss/fieldpage.scss
  frontends/infinite-corridor/src/scss/form.scss
  frontends/infinite-corridor/src/scss/header.scss
  frontends/infinite-corridor/src/scss/homepage.scss
  frontends/infinite-corridor/src/scss/learning-resources.scss
  frontends/infinite-corridor/src/scss/main-search.scss
  frontends/infinite-corridor/src/scss/mui.scss
  frontends/infinite-corridor/src/scss/searchpage.scss
  frontends/infinite-corridor/src/scss/theme.scss
  frontends/infinite-corridor/src/scss/widgets.scss
  frontends/ol-search-ui/assets/learning-resource-card.scss
  frontends/ol-search-ui/assets/learning-resource-drawer.scss
  frontends/ol-util/assets/card.scss
  frontends/ol-widgets/assets/widgets.scss
  frontends/open-discussions/.sass-lint.yml
  frontends/open-discussions/package.json
  frontends/open-discussions/scss/course-searchbox.scss
  package.json
  yarn.lock
Labels: Waiting on Author

#3851 Remove yarn postinstall script
  .github/workflows/ci.yml
  package.json
Labels: Waiting on Author

#3855 Add more valid text file types
  course_catalog/constants.py
  course_catalog/etl/utils_test.py
Labels: Needs Review

#3850 Learn search results list dates are different than default drawer details dates
  frontends/ol-search-ui/src/components/LearningResourceCard.tsx
  frontends/ol-search-ui/src/util.tsx
  frontends/open-discussions/src/components/LearningResourceCard.js
  frontends/open-discussions/src/components/LearningResourceCard_test.js
  frontends/open-discussions/src/lib/learning_resources.js
  frontends/open-discussions/src/lib/learning_resources_test.js
Labels: Waiting on Author

#3861 More efficient download and processing of edx content archives
  course_catalog/etl/edx_shared.py
  course_catalog/etl/utils.py
  course_catalog/etl/utils_test.py
  search/tasks.py
  search/tasks_test.py
Labels: Waiting on Author

#3869 fix flaky test: use standard date format for cards
  frontends/open-discussions/src/components/LearningResourceCard_test.js
  frontends/open-discussions/src/factories/learning_resources.js
  frontends/open-discussions/src/lib/constants.js
  frontends/open-discussions/src/lib/learning_resources.js
Labels: Waiting on Author

#3874 stop building individual ts packages
  frontends/infinite-corridor/src/api/fields/factories.ts
  frontends/infinite-corridor/src/pages/HomePage.test.tsx
  frontends/infinite-corridor/src/pages/SearchPage.test.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldAppearanceForm.test.tsx
  frontends/infinite-corridor/src/pages/field-details/EditFieldBasicForm.test.tsx
  frontends/infinite-corridor/src/pages/field-details/FieldPage.test.tsx
  frontends/infinite-corridor/src/pages/field-details/WidgetsList.test.tsx
  frontends/infinite-corridor/src/test-utils/setupJest.ts
  frontends/ol-forms/package.json
  frontends/ol-search-ui/package.json
  frontends/ol-search-ui/src/components/ExpandedLearningResourceDisplay.test.tsx
  frontends/ol-search-ui/src/components/index.ts
  frontends/ol-search-ui/src/factories.ts
  frontends/ol-util/package.json
  frontends/ol-widgets/package.json
  frontends/ol-widgets/src/factories.ts
  frontends/ol-widgets/src/index.ts
  package.json
Labels: Waiting on Author

#3877 2 New API filters for new open - offered_by and audience
  course_catalog/filters.py
  course_catalog/filters_test.py
  course_catalog/views.py
  open_discussions/settings.py
Labels: Needs Review

#3880 More improvements in memory usage for edx content archive processing
  course_catalog/etl/edx_shared.py
  course_catalog/etl/edx_shared_test.py
  course_catalog/etl/loaders.py
  course_catalog/etl/utils.py
  course_catalog/etl/utils_test.py
  course_catalog/etl/xpro.py
  course_catalog/etl/xpro_test.py
  course_catalog/tasks.py
  course_catalog/tasks_test.py
  fixtures/aws.py
Labels: Needs Review, Waiting on Author

#3889 Set concurrency=4 (2x CPU) for the celery extra_worker_performance dyno
  Procfile
Labels: Needs Review

#3891 Revert "Set concurrency=4 (2x CPU) for the extra_worker_performance d…
  Procfile
Labels: Needs Review

#3843 Open discussions Elastic/Opensearch performance updates
  app.json
  open_discussions/settings.py
  search/connection.py
  search/indexing_api.py
Labels: enhancement, DevOps

#3895 fix: Nonbreaking typo in app.json for new ES env var.
  app.json
Labels: bug, Waiting on Author, DevOps

#3900 Jw/drf spectacular
  course_catalog/serializers.py
  course_catalog/urls.py
  open_discussions/settings.py
  open_discussions/settings_spectacular.py
  requirements.in
  requirements.txt
Labels: Waiting on Author
